/*
 * Copyright (c) 2026 Oracle and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.helidon.data.jdbc;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * A <dfn>view</dfn> of a {@link Connection}, representing it only as a <dfn>factory</dfn> for JDBC {@link Statement},
 * {@link PreparedStatement}, and {@link CallableStatement} instances.
 *
 * <p>Each method in this interface corresponds to a {@link Statement}-creating <dfn>factory method</dfn> in the <a
 * href="https://docs.oracle.com/en/java/javase/26/docs/api/java.sql/java/sql/package-summary.html">JDBC 4.5</a> version
 * of the {@link Connection} interface.</p>
 *
 * <p>As with all constructs related to JDBC, a {@link JdbcStatementFactory} is not necessarily safe for concurrent use
 * by multiple threads unless explicitly noted.</p>
 */
@io.helidon.common.Api.Internal
public sealed interface JdbcStatementFactory permits JdbcStatementFactoryImpl {

    /**
     * Creates a {@link Statement}.
     *
     * @return a new statement
     * @throws SQLException if a database error occurs
     */
    Statement createStatement() throws SQLException;

    /**
     * Creates a {@link Statement} with the supplied result-set type and concurrency.
     *
     * @param resultSetType result-set type
     * @param resultSetConcurrency result-set concurrency
     * @return a new statement
     * @throws SQLException if a database error occurs
     */
    Statement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException;

    /**
     * Creates a {@link Statement} with the supplied result-set type, concurrency, and holdability.
     *
     * @param resultSetType result-set type
     * @param resultSetConcurrency result-set concurrency
     * @param resultSetHoldability result-set holdability
     * @return a new statement
     * @throws SQLException if a database error occurs
     */
    Statement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability)
        throws SQLException;

    /**
     * Creates a {@link PreparedStatement} for the supplied SQL.
     *
     * @param sql SQL statement text
     * @return a new prepared statement
     * @throws SQLException if a database error occurs
     */
    PreparedStatement prepareStatement(String sql) throws SQLException;

    /**
     * Creates a {@link PreparedStatement} for the supplied SQL and generated-keys mode.
     *
     * @param sql SQL statement text
     * @param autoGeneratedKeys generated-keys mode
     * @return a new prepared statement
     * @throws SQLException if a database error occurs
     */
    PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException;

    /**
     * Creates a {@link PreparedStatement} for the supplied SQL and returned-column indexes.
     *
     * @param sql SQL statement text
     * @param columnIndexes returned-column indexes
     * @return a new prepared statement
     * @throws SQLException if a database error occurs
     */
    PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException;

    /**
     * Creates a {@link PreparedStatement} for the supplied SQL and returned-column names.
     *
     * @param sql SQL statement text
     * @param columnNames returned-column names
     * @return a new prepared statement
     * @throws SQLException if a database error occurs
     */
    PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException;

    /**
     * Creates a {@link PreparedStatement} for the supplied SQL with the supplied result-set type and concurrency.
     *
     * @param sql SQL statement text
     * @param resultSetType result-set type
     * @param resultSetConcurrency result-set concurrency
     * @return a new prepared statement
     * @throws SQLException if a database error occurs
     */
    PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) throws SQLException;

    /**
     * Creates a {@link PreparedStatement} for the supplied SQL with the supplied result-set shape.
     *
     * @param sql SQL statement text
     * @param resultSetType result-set type
     * @param resultSetConcurrency result-set concurrency
     * @param resultSetHoldability result-set holdability
     * @return a new prepared statement
     * @throws SQLException if a database error occurs
     */
    PreparedStatement prepareStatement(String sql,
                                       int resultSetType,
                                       int resultSetConcurrency,
                                       int resultSetHoldability) throws SQLException;

    /**
     * Creates a {@link CallableStatement} for the supplied SQL.
     *
     * @param sql SQL statement text
     * @return a new callable statement
     * @throws SQLException if a database error occurs
     */
    CallableStatement prepareCall(String sql) throws SQLException;

    /**
     * Creates a {@link CallableStatement} for the supplied SQL with the supplied result-set type and concurrency.
     *
     * @param sql SQL statement text
     * @param resultSetType result-set type
     * @param resultSetConcurrency result-set concurrency
     * @return a new callable statement
     * @throws SQLException if a database error occurs
     */
    CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency) throws SQLException;

    /**
     * Creates a {@link CallableStatement} for the supplied SQL with the supplied result-set shape.
     *
     * @param sql SQL statement text
     * @param resultSetType result-set type
     * @param resultSetConcurrency result-set concurrency
     * @param resultSetHoldability result-set holdability
     * @return a new callable statement
     * @throws SQLException if a database error occurs
     */
    CallableStatement prepareCall(String sql,
                                  int resultSetType,
                                  int resultSetConcurrency,
                                  int resultSetHoldability) throws SQLException;

    /**
     * Returns a new {@link JdbcStatementFactory} backed by the supplied {@link Connection}.
     *
     * @param connection connection to adapt; must not be {@code null}
     * @return a new statement factory
     */
    static JdbcStatementFactory of(Connection connection) {
        return new JdbcStatementFactoryImpl(connection);
    }

}
