/*
 * Copyright (c) 2026 Oracle and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.helidon.data.jdbc;

import java.sql.CallableStatement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import java.util.Optional;
import java.util.Spliterator;
import java.util.function.Consumer;
import java.util.stream.Stream;
import java.util.stream.StreamSupport;

import io.helidon.data.jdbc.function.JdbcConsumer;
import io.helidon.data.jdbc.function.JdbcFunction;
import io.helidon.data.jdbc.function.JdbcRunnable;

import static java.util.Objects.requireNonNull;

/**
 * An object representing the family of results any collection of {@link Statement} {@linkplain
 * Statement#execute(String) execution}s, or {@link java.sql.PreparedStatement} {@linkplain
 * java.sql.PreparedStatement#execute() executions (including <code>CallableStatement</code> executions)}, may produce.
 *
 * <p>As with all constructs related to JDBC, a {@link JdbcResults} is not necessarily safe for concurrent use by
 * multiple threads unless explicitly noted.</p>
 *
 * @see #advance()
 * @see #get()
 * @see JdbcResult
 * @see #of(Preparation)
 */
public interface JdbcResults extends JdbcOpen, JdbcWarningsBearing {

    /**
     * Advances to the next {@link JdbcResult} in the notional chain of results and returns {@code true} if and only if
     * there is one.
     *
     * <p>A {@link JdbcResults} is positioned <em>before</em> the notional first result. If {@link #advance()} is never
     * called, {@link #get()} will always return an {@linkplain Optional#isEmpty() empty} {@link Optional}.</p>
     *
     * <p>If this method returns {@code true}, then the {@link Optional} returned by {@link #get()} will be {@linkplain
     * Optional#isPresent() present}.</p>
     *
     * @return {@code true} if and only if advancement was successful
     * @throws IllegalStateException if this {@link JdbcResults} is {@linkplain #close() closed}
     * @throws java.sql.BatchUpdateException if advancement resulted in a batch execution and it failed
     * @throws SQLException if a database error occurs
     * @see #get()
     */
    boolean advance() throws SQLException;

    /**
     * Returns {@code true} if and only if this {@link JdbcResults} is {@linkplain #close() closed}.
     *
     * <p>This operation is idempotent.</p>
     *
     * @return {@code true} if and only if this {@link JdbcResults} is {@linkplain #close() closed}.
     * @throws SQLException if a database error occurs
     * @see #close()
     */
    boolean closed() throws SQLException;

    /**
     * Returns the current {@link JdbcResult} if {@link #advance()} has been called and there is one.
     *
     * <p>If this method returns an {@linkplain Optional#isEmpty() empty} {@link Optional}, then either {@link
     * #advance()} has not yet been called, or an invocation of {@link #advance()} returned {@code false}.</p>
     *
     * @return a non-{@code null} {@link Optional} containing the current {@link JdbcResult} if there is one
     * @throws IllegalStateException if this {@link JdbcResults} is {@linkplain #close() closed}
     * @throws SQLException if a database error occurs
     * @see #advance()
     * @see JdbcResult
     */
    Optional<JdbcResult> get() throws SQLException;

    /**
     * Returns any keys generated by the statement execution.
     *
     * @return a non-{@code null} {@link Optional} containing any keys generated by the statement execution
     * @throws IllegalStateException if this {@link JdbcResults} is {@linkplain #close() closed}
     * @throws SQLException if a database error occurs
     * @see Statement#getGeneratedKeys()
     */
    Optional<ResultSet> keys() throws SQLException;

    @Override // JdbcOpen
    JdbcResults onClose(JdbcRunnable closeAction) throws SQLException;

    /**
     * A convenience method that performs an action for each remaining {@link JdbcResult} of a particular type.
     *
     * @param <JR> a {@link JdbcResult} subtype
     * @param type a non-{@code null} {@link Class} identifying a {@link JdbcResult} subtype
     * @param c a non-{@code null} {@link JdbcConsumer} accepting a specific type of {@link JdbcResult}
     * @throws NullPointerException if any argument is {@code null}
     * @throws IllegalStateException if a {@link JdbcResult} not of the appropriate type is encountered, or if this
     * {@link JdbcResults} is {@linkplain #closed() closed}
     * @throws SQLException if a database error occurs
     */
    default <JR extends JdbcResult> void forEachRemaining(Class<JR> type, JdbcConsumer<? super JR> c) throws SQLException {
        while (this.advance()) {
            JdbcResult result = this.get().orElse(null);
            if (!type.isInstance(result)) {
                throw new IllegalStateException("Expected " + type.getSimpleName()
                                                + ", got " + (result == null ? "no result" : result.getClass().getSimpleName()));
            }
            c.accept(type.cast(result));
        }
    }

    /**
     * A convenience method that adapts the supplied {@link JdbcConsumer} to a void-returning {@link JdbcFunction} and
     * calls the {@link #mapNext(Class, JdbcFunction)} with the supplied {@link Class} and the adapted {@link
     * JdbcConsumer}.
     *
     * @param <JR> a {@link JdbcResult} subtype
     * @param type a non-{@code null} {@link Class} identifying a {@link JdbcResult} subtype
     * @param c a non-{@code null} {@link JdbcConsumer} accepting a specific type of {@link JdbcResult}
     * @throws NullPointerException if any argument is {@code null}
     * @throws IllegalStateException if there is not a next {@link JdbcResult} of the appropriate type remaining, or if
     * this {@link JdbcResults} is {@linkplain #closed() closed}
     * @throws SQLException if a database error occurs
     * @see #mapNext(Class, JdbcFunction)
     */
    default <JR extends JdbcResult> void forNext(Class<JR> type, JdbcConsumer<? super JR> c) throws SQLException {
        this.mapNext(type, jr -> {
                c.accept(jr);
                return null;
            });
    }

    /**
     * A convenience method that adapts the supplied {@link JdbcConsumer} to a void-returning {@link JdbcFunction} and
     * calls the {@link #mapOnly(Class, JdbcFunction)} method with the supplied {@link Class} and the adapted {@link
     * JdbcConsumer}.
     *
     * <p><strong>This method (indirectly) attempts two additional {@linkplain #advance() advancements}</strong> and
     * throws an {@link IllegalStateException} if the second is successful.</p>
     *
     * @param <JR> a {@link JdbcResult} subtype
     * @param type a non-{@code null} {@link Class} identifying a {@link JdbcResult} subtype
     * @param c a non-{@code null} {@link JdbcConsumer} accepting a specific type of {@link JdbcResult}
     * @throws NullPointerException if any argument is {@code null}
     * @throws IllegalStateException if there is not exactly one {@link JdbcResult} of the appropriate type, or if this
     * {@link JdbcResults} is {@linkplain #closed() closed}
     * @throws SQLException if a database error occurs
     * @see #mapOnly(Class, JdbcFunction)
     */
    default <JR extends JdbcResult> void forOnly(Class<JR> type, JdbcConsumer<? super JR> c) throws SQLException {
        this.mapOnly(type, jr -> {
                c.accept(jr);
                return null;
            });
    }

    /**
     * A convenience method that adapts the supplied {@link JdbcConsumer} to a void-returning {@link JdbcFunction} and
     * calls the {@link #mapOnlyRemaining(Class, JdbcFunction)} with the supplied {@link Class} and the adapted {@link
     * JdbcConsumer}.
     *
     * <p><strong>This method (indirectly) attempts another {@linkplain #advance() advancement}</strong> and throws an
     * {@link IllegalStateException} if it is successful.</p>
     *
     * @param <JR> a {@link JdbcResult} subtype
     * @param type a non-{@code null} {@link Class} identifying a {@link JdbcResult} subtype
     * @param c a non-{@code null} {@link JdbcConsumer} accepting a specific type of {@link JdbcResult}
     * @throws NullPointerException if any argument is {@code null}
     * @throws IllegalStateException if there is not exactly one {@link JdbcResult} of the appropriate type remaining,
     * or if this {@link JdbcResults} is {@linkplain #closed() closed}
     * @throws SQLException if a database error occurs
     * @see #mapOnlyRemaining(Class, JdbcFunction)
     */
    default <JR extends JdbcResult> void forOnlyRemaining(Class<JR> type, JdbcConsumer<? super JR> c) throws SQLException {
        this.mapOnlyRemaining(type, jr -> {
                c.accept(jr);
                return null;
            });
    }

    /**
     * A convenience method that returns the result of invoking the {@link #get()} method as an instance of the supplied
     * {@code type}, if that condition can be satisfied.
     *
     * <p>The default implementation:</p>
     *
     * <ol>
     * <li>Invokes the {@link #get()} method</li>
     * <li>Invokes the {@link Optional#filter(java.util.function.Predicate)} method with {@link Class#isInstance(Object)
     * type::isInstance} as the predicate</li>
     * <li>Invokes the {@link Optional#map(java.util.function.Function)} method on the resulting {@link Optional} with
     * {@link Class#cast(Object) type::cast} as the mapping function</li>
     * <li>Returns the result</li>
     * </ol>
     *
     * @param <JR> a {@link JdbcResult} subtype
     * @param type a non-{@code null} {@link Class}
     * @return a non-{@code null} {@link Optional}
     * @throws NullPointerException if {@code type} is {@code null}
     * @throws SQLException if a database error occurs
     * @see #get()
     */
    default <JR extends JdbcResult> Optional<JR> getAs(Class<JR> type) throws SQLException {
        return this.get()
            .filter(type::isInstance)
            .map(type::cast);
    }

    /**
     * A convenience method that {@linkplain #advance() advances} this {@link JdbcResult}, and, assuming it is
     * successful, {@linkplain #get() gets the current result}, and, assuming it the proper {@link JdbcResult} subtype,
     * passes it to the supplied mapping function and returns the result.
     *
     * @param <JR> a {@link JdbcResult} subtype
     * @param <R> the mapped type
     * @param type a non-{@code null} {@link Class} identifying a {@link JdbcResult} subtype
     * @param f a non-{@code null} {@link JdbcFunction} accepting a specific type of {@link JdbcResult} responsible for
     * mapping it
     * @return the mapping result
     * @throws NullPointerException if any argument is {@code null}
     * @throws IllegalStateException if there is not a next {@link JdbcResult} of the appropriate type remaining, or if
     * this {@link JdbcResults} is {@linkplain #closed() closed}
     * @throws SQLException if a database error occurs
     */
    default <JR extends JdbcResult, R> R mapNext(Class<JR> type, JdbcFunction<? super JR, ? extends R> f) throws SQLException {
        if (!this.advance()) {
            throw new IllegalStateException("Expected at least one " + type.getSimpleName() + ", but there were no results");
        }
        JdbcResult result = this.get().orElse(null);
        if (!type.isInstance(result)) {
            throw new IllegalStateException("Expected at least one " + type.getSimpleName()
                                            + ", got " + (result == null ? "no result" : result.getClass().getSimpleName()));
        }
        return f.apply(type.cast(result));
    }

    /**
     * A convenience method that checks to see if the return value from an invocation of the {@link #get()} method
     * {@linkplain Optional#isEmpty() is empty}, and, if so, invokes the {@link #mapOnlyRemaining(Class, JdbcFunction)}
     * method and returns its results.
     *
     * <p><strong>This method (indirectly) attempts two additional {@linkplain #advance() advancements}</strong> and
     * throws an {@link IllegalStateException} if the second is successful.</p>
     *
     * @param <JR> a {@link JdbcResult} subtype
     * @param <R> the mapped type
     * @param type a non-{@code null} {@link Class} identifying a {@link JdbcResult} subtype
     * @param f a non-{@code null} {@link JdbcFunction} accepting a specific type of {@link JdbcResult} responsible for
     * mapping it
     * @return the mapping result
     * @throws NullPointerException if any argument is {@code null}
     * @throws IllegalStateException if there is not exactly one {@link JdbcResult} of the appropriate type, or if this
     * {@link JdbcResults} is {@linkplain #closed() closed}
     * @throws SQLException if a database error occurs
     * @see #mapOnlyRemaining(Class, JdbcFunction)
     * @see #get()
     */
    default <JR extends JdbcResult, R> R mapOnly(Class<JR> type, JdbcFunction<? super JR, ? extends R> f) throws SQLException {
        if (this.get().isEmpty()) {
            return this.mapOnlyRemaining(type, f);
        } else {
            throw new IllegalStateException("Expected exactly one " + type.getSimpleName()
                                            + ", but there were additional results");
        }
    }

    /**
     * A convenience method that calls the {@link #mapNext(Class, JdbcFunction)} method with the supplied arguments,
     * presuming that the resulting {@linkplain #advance() advancement} will be the last one, and returns the return
     * value.
     *
     * <p><strong>This method attempts another {@linkplain #advance() advancement}</strong> and throws an {@link
     * IllegalStateException} if it is successful.</p>
     *
     * @param <JR> a {@link JdbcResult} subtype
     * @param <R> the mapped type
     * @param type a non-{@code null} {@link Class} identifying a {@link JdbcResult} subtype
     * @param f a non-{@code null} {@link JdbcFunction} accepting a specific type of {@link JdbcResult} responsible for
     * mapping it
     * @return the mapping result
     * @throws NullPointerException if any argument is {@code null}
     * @throws IllegalStateException if there is not exactly one {@link JdbcResult} of the appropriate type remaining,
     * or if this {@link JdbcResults} is {@linkplain #closed() closed}
     * @throws SQLException if a database error occurs
     * @see #mapNext(Class, JdbcFunction)
     */
    default <JR extends JdbcResult, R> R mapOnlyRemaining(Class<JR> type, JdbcFunction<? super JR, ? extends R> f)
        throws SQLException {
        R returnValue = this.mapNext(type, f);
        if (this.advance()) {
            throw new IllegalStateException("Expected exactly one " + type.getSimpleName()
                                            + ", but there were additional results");
        }
        return returnValue;
    }

    /**
     * Returns a new {@link Spliterator Spliterator&lt;JdbcResult&gt;}.
     *
     * <p>The returned {@link Spliterator} may throw {@link UncheckedSQLException}s in addition to any other exceptions
     * it may throw.</p>
     *
     * @return a new {@link Spliterator Spliterator&lt;JdbcResult&gt;}
     * @see Spliterator
     * @see UncheckedSQLException
     */
    default Spliterator<JdbcResult> spliterator() {
        return new Spliterator<>() {
            @Override // Spliterator<JdbcResult>
            public Spliterator<JdbcResult> trySplit() {
                return null; // cannot be parallel
            }
            @Override // Spliterator<JdbcResult>
            public long estimateSize() {
                return Long.MAX_VALUE; // unknown
            }
            @Override // Spliterator<JdbcResult>
            public int characteristics() {
                return ORDERED | NONNULL;
            }
            @Override // Spliterator<JdbcResult>
            public void forEachRemaining(Consumer<? super JdbcResult> action) {
                try {
                    JdbcResults.this.<JdbcResult>forEachRemaining(JdbcResult.class, action::accept);
                } catch (SQLException e) {
                    throw new UncheckedSQLException(e);
                }
            }
            @Override // Spliterator<JdbcResult>
            public boolean tryAdvance(Consumer<? super JdbcResult> action) {
                try {
                    if (JdbcResults.this.advance()) {
                        action.accept(JdbcResults.this.get().orElseThrow(AssertionError::new));
                        return true;
                    } else {
                        return false;
                    }
                } catch (SQLException e) {
                    throw new UncheckedSQLException(e);
                }
            }
        };
    }

    /**
     * Returns a non-{@code null}, sequential {@link Stream Stream&lt;JdbcResult&gt;} of this {@link JdbcResults}'
     * contents.
     *
     * <p>When the returned {@link Stream} is {@linkplain Stream#close() closed}, this {@link JdbcResults} will be
     * {@linkplain #close() closed}.</p>
     *
     * @return a non-{@code null} {@link Stream}
     * @see #close()
     * @see #spliterator()
     * @see StreamSupport#stream(Spliterator, boolean)
     * @see Stream#onClose(Runnable)
     * @see Stream#close()
     */
    default Stream<JdbcResult> stream() {
        return StreamSupport.stream(this.spliterator(),
                                    false /* deliberately not parallel */)
            .onClose(((JdbcRunnable) this::close).toRunnable());
    }


    /*
     * Static methods.
     */


    /**
     * Returns a new {@link JdbcResults} representing the potentially many results produced by the execution of the
     * supplied {@link Preparation}.
     *
     * @param preparation a non-{@code null} {@link Preparation}
     * @return a new {@link JdbcResult}; callers are responsible for {@linkplain #close() closing it}
     * @throws NullPointerException if {@code preparation} is {@code null}
     */
    static JdbcResults of(Preparation preparation) {
        return new JdbcResultsImpl(preparation);
    }

    /**
     * Returns a new {@link JdbcResults} representing the potentially many results produced by the executions of the
     * supplied {@link Preparation}s.
     *
     * @param preparations a non-{@code null} {@link List} of {@link Preparation}s
     * @return a new {@link JdbcResult}; callers are responsible for {@linkplain #close() closing it}
     * @throws NullPointerException if {@code preparations} is {@code null}
     */
    static JdbcResults of(List<? extends Preparation> preparations) {
        return new JdbcResultsImpl(preparations);
    }


    /*
     * Inner and nested classes.
     */


    /**
     * A preparation of an imminent {@link JdbcResults}.
     *
     * @see #of(Preparation)
     */
    final class Preparation {

        private final Statement statement;

        private final boolean batch;

        private final String sql;

        private final GeneratedKeysBehavior generatedKeysBehavior;

        private final int[] columnIndices;

        private final String[] columnNames;

        private final JdbcResult jdbcResult;

        private final ResultsAdvancementBehavior resultsAdvancementBehavior;

        private final int[] outParameterIndices;

        private static final int[] EMPTY_INT_ARRAY = new int[0];

        private static final String[] EMPTY_STRING_ARRAY = new String[0];

        /**
         * Creates a new {@link Preparation}.
         *
         * @param ps a non-{@code null} {@link PreparedStatement}
         * @throws NullPointerException if any argument is {@code null}
         */
        public Preparation(PreparedStatement ps) {
            this(ps,
                 false,
                 null,
                 GeneratedKeysBehavior.NONE,
                 EMPTY_INT_ARRAY,
                 EMPTY_STRING_ARRAY,
                 null,
                 ResultsAdvancementBehavior.CLOSE_CURRENT_RESULT,
                 EMPTY_INT_ARRAY);
        }

        /**
         * Creates a new {@link Preparation}.
         *
         * @param ps a non-{@code null} {@link PreparedStatement}
         * @param resultsAdvancementBehavior a non-{@code null} {@link ResultsAdvancementBehavior}; normally {@link
         * ResultsAdvancementBehavior#CLOSE_CURRENT_RESULT}
         * @throws NullPointerException if any argument is {@code null}
         */
        public Preparation(PreparedStatement ps, ResultsAdvancementBehavior resultsAdvancementBehavior) {
            this(ps,
                 false,
                 null,
                 GeneratedKeysBehavior.NONE,
                 EMPTY_INT_ARRAY,
                 EMPTY_STRING_ARRAY,
                 null,
                 resultsAdvancementBehavior,
                 EMPTY_INT_ARRAY);
        }

        /**
         * Creates a new {@link Preparation}.
         *
         * @param cs a non-{@code null} {@link CallableStatement}
         * @param outParameterIndices a non-{@code null} array of {@code 1}-based already registered {@code OUT}
         * parameters in the supplied {@link CallableStatement}
         * @throws NullPointerException if any argument is {@code null}
         */
        public Preparation(CallableStatement cs, int[] outParameterIndices) {
            this(cs,
                 false,
                 null,
                 GeneratedKeysBehavior.NONE,
                 EMPTY_INT_ARRAY,
                 EMPTY_STRING_ARRAY,
                 null,
                 ResultsAdvancementBehavior.CLOSE_CURRENT_RESULT,
                 outParameterIndices);
        }

        /**
         * Creates a new {@link Preparation}.
         *
         * @param cs a non-{@code null} {@link CallableStatement}
         * @param resultsAdvancementBehavior a non-{@code null} {@link ResultsAdvancementBehavior}; normally {@link
         * ResultsAdvancementBehavior#CLOSE_CURRENT_RESULT}
         * @param outParameterIndices a non-{@code null} array of {@code 1}-based already registered {@code OUT}
         * parameters in the supplied {@link CallableStatement}
         * @throws NullPointerException if any argument is {@code null}
         */
        public Preparation(CallableStatement cs,
                           ResultsAdvancementBehavior resultsAdvancementBehavior,
                           int[] outParameterIndices) {
            this(cs,
                 false,
                 null,
                 GeneratedKeysBehavior.NONE,
                 EMPTY_INT_ARRAY,
                 EMPTY_STRING_ARRAY,
                 null,
                 resultsAdvancementBehavior,
                 outParameterIndices);
        }

        /**
         * Creates a new {@link Preparation}.
         *
         * @param s a non-{@code null} {@link Statement}
         * @param batchExecution a {@code boolean} which, if {@code true}, indicates that a {@linkplain
         * Statement#executeLargeBatch() batch execution} is being requested; if {@code false} then {@code s} must be a
         * {@link PreparedStatement}
         * @throws NullPointerException if any argument is {@code null}
         * @throws IllegalArgumentException if {@code batchExecution} is {@code false} and {@code s} is not a {@link PreparedStatement}
         */
        public Preparation(Statement s, boolean batchExecution) {
            this(s,
                 batchExecution,
                 null,
                 GeneratedKeysBehavior.NONE,
                 EMPTY_INT_ARRAY,
                 EMPTY_STRING_ARRAY,
                 null,
                 ResultsAdvancementBehavior.CLOSE_CURRENT_RESULT,
                 EMPTY_INT_ARRAY);
        }

        /**
         * Creates a new {@link Preparation}.
         *
         * @param s a non-{@code null} {@link Statement}
         * @param sql a non-{@code null} SQL statement to execute
         * @throws NullPointerException if any argument is {@code null}
         */
        public Preparation(Statement s, String sql) {
            this(s,
                 false,
                 sql,
                 GeneratedKeysBehavior.NONE,
                 EMPTY_INT_ARRAY,
                 EMPTY_STRING_ARRAY,
                 null,
                 ResultsAdvancementBehavior.CLOSE_CURRENT_RESULT,
                 EMPTY_INT_ARRAY);
        }

        /**
         * Creates a new {@link Preparation}.
         *
         * @param s a non-{@code null} {@link Statement}
         * @param sql a non-{@code null} SQL statement to execute
         * @param resultsAdvancementBehavior a non-{@code null} {@link ResultsAdvancementBehavior}; normally {@link
         * ResultsAdvancementBehavior#CLOSE_CURRENT_RESULT}
         * @throws NullPointerException if any argument is {@code null}
         */
        public Preparation(Statement s, String sql, ResultsAdvancementBehavior resultsAdvancementBehavior) {
            this(s,
                 false,
                 sql,
                 GeneratedKeysBehavior.NONE,
                 EMPTY_INT_ARRAY,
                 EMPTY_STRING_ARRAY,
                 null,
                 resultsAdvancementBehavior,
                 EMPTY_INT_ARRAY);
        }

        /**
         * Creates a new {@link Preparation}.
         *
         * @param s a non-{@code null} {@link Statement}
         * @param sql a non-{@code null} SQL statement to execute
         * @param generatedKeysBehavior a non-{@code null} {@link GeneratedKeysBehavior}
         * @throws NullPointerException if any argument is {@code null}
         */
        public Preparation(Statement s, String sql, GeneratedKeysBehavior generatedKeysBehavior) {
            this(s,
                 false,
                 sql,
                 generatedKeysBehavior,
                 EMPTY_INT_ARRAY,
                 EMPTY_STRING_ARRAY,
                 null,
                 ResultsAdvancementBehavior.CLOSE_CURRENT_RESULT,
                 EMPTY_INT_ARRAY);
        }

        /**
         * Creates a new {@link Preparation}.
         *
         * @param s a non-{@code null} {@link Statement}
         * @param sql a non-{@code null} SQL statement to execute
         * @param generatedKeysBehavior a non-{@code null} {@link GeneratedKeysBehavior}
         * @param resultsAdvancementBehavior a non-{@code null} {@link ResultsAdvancementBehavior}; normally {@link
         * ResultsAdvancementBehavior#CLOSE_CURRENT_RESULT}
         * @throws NullPointerException if any argument is {@code null}
         */
        public Preparation(Statement s,
                           String sql,
                           GeneratedKeysBehavior generatedKeysBehavior,
                           ResultsAdvancementBehavior resultsAdvancementBehavior) {
            this(s,
                 false,
                 sql,
                 generatedKeysBehavior,
                 EMPTY_INT_ARRAY,
                 EMPTY_STRING_ARRAY,
                 null,
                 resultsAdvancementBehavior,
                 EMPTY_INT_ARRAY);
        }

        /**
         * Creates a new {@link Preparation}.
         *
         * @param s a non-{@code null} {@link Statement}
         * @param sql a non-{@code null} SQL statement to execute
         * @param columnIndices an array of the indexes of the columns in the inserted row that should be made available for
         * retrieval by a call to the method {@link Statement#getGeneratedKeys()}
         * @throws NullPointerException if any argument is {@code null}
         */
        public Preparation(Statement s, String sql, int[] columnIndices) {
            this(s,
                 false,
                 sql,
                 GeneratedKeysBehavior.RETURN,
                 columnIndices,
                 EMPTY_STRING_ARRAY,
                 null,
                 ResultsAdvancementBehavior.CLOSE_CURRENT_RESULT,
                 EMPTY_INT_ARRAY);
        }

        /**
         * Creates a new {@link Preparation}.
         *
         * @param s a non-{@code null} {@link Statement}
         * @param sql a non-{@code null} SQL statement to execute
         * @param columnIndices an array of the indexes of the columns in the inserted row that should be made available for
         * retrieval by a call to the method {@link Statement#getGeneratedKeys()}
         * @param resultsAdvancementBehavior a non-{@code null} {@link ResultsAdvancementBehavior}; normally {@link
         * ResultsAdvancementBehavior#CLOSE_CURRENT_RESULT}
         * @throws NullPointerException if any argument is {@code null}
         */
        public Preparation(Statement s, String sql, int[] columnIndices, ResultsAdvancementBehavior resultsAdvancementBehavior) {
            this(s,
                 false,
                 sql,
                 GeneratedKeysBehavior.RETURN,
                 columnIndices,
                 EMPTY_STRING_ARRAY,
                 null,
                 resultsAdvancementBehavior,
                 EMPTY_INT_ARRAY);
        }

        /**
         * Creates a new {@link Preparation}.
         *
         * @param s a non-{@code null} {@link Statement}
         * @param sql a non-{@code null} SQL statement to execute
         * @param columnNames an array of the names of the columns in the inserted row that should be made available for
         * retrieval by a call to the method {@link Statement#getGeneratedKeys()}
         * @throws NullPointerException if any argument is {@code null}
         */
        public Preparation(Statement s, String sql, String[] columnNames) {
            this(s,
                 false,
                 sql,
                 GeneratedKeysBehavior.RETURN,
                 EMPTY_INT_ARRAY,
                 columnNames,
                 null,
                 ResultsAdvancementBehavior.CLOSE_CURRENT_RESULT,
                 EMPTY_INT_ARRAY);
        }

        /**
         * Creates a new {@link Preparation}.
         *
         * @param s a non-{@code null} {@link Statement}
         * @param sql a non-{@code null} SQL statement to execute
         * @param columnNames an array of the names of the columns in the inserted row that should be made available for
         * retrieval by a call to the method {@link Statement#getGeneratedKeys()}
         * @param resultsAdvancementBehavior a non-{@code null} {@link ResultsAdvancementBehavior}; normally {@link
         * ResultsAdvancementBehavior#CLOSE_CURRENT_RESULT}
         * @throws NullPointerException if any argument is {@code null}
         */
        public Preparation(Statement s, String sql, String[] columnNames, ResultsAdvancementBehavior resultsAdvancementBehavior) {
            this(s,
                 false,
                 sql,
                 GeneratedKeysBehavior.RETURN,
                 EMPTY_INT_ARRAY,
                 columnNames,
                 null,
                 resultsAdvancementBehavior,
                 EMPTY_INT_ARRAY);
        }

        /**
         * Creates a new {@link Preparation}.
         *
         * @param rs a non-{@code null} {@link ResultSet}
         * @throws NullPointerException if any argument is {@code null}
         * @throws SQLException if a database error occurs
         */
        public Preparation(ResultSet rs) throws SQLException {
            this(rs.getStatement(),
                 false,
                 null,
                 GeneratedKeysBehavior.NONE,
                 EMPTY_INT_ARRAY,
                 EMPTY_STRING_ARRAY,
                 JdbcResultSet.of(rs),
                 ResultsAdvancementBehavior.CLOSE_CURRENT_RESULT,
                 EMPTY_INT_ARRAY);
        }

        /**
         * Creates a new {@link Preparation}.
         *
         * @param rs a non-{@code null} {@link ResultSet}
         * @param resultsAdvancementBehavior a non-{@code null} {@link ResultsAdvancementBehavior}; normally {@link
         * ResultsAdvancementBehavior#CLOSE_CURRENT_RESULT}
         * @throws NullPointerException if any argument is {@code null}
         * @throws SQLException if a database error occurs
         */
        public Preparation(ResultSet rs, ResultsAdvancementBehavior resultsAdvancementBehavior) throws SQLException {
            this(rs.getStatement(),
                 false,
                 null,
                 GeneratedKeysBehavior.NONE,
                 EMPTY_INT_ARRAY,
                 EMPTY_STRING_ARRAY,
                 JdbcResultSet.of(rs),
                 resultsAdvancementBehavior,
                 EMPTY_INT_ARRAY);
        }

        private Preparation(Statement statement,
                            boolean batch,
                            String sql,
                            GeneratedKeysBehavior generatedKeysBehavior,
                            int[] columnIndices,
                            String[] columnNames,
                            JdbcResult jdbcResult,
                            ResultsAdvancementBehavior resultsAdvancementBehavior,
                            int[] outParameterIndices) {
            this.statement = requireNonNull(statement, "statement");
            if (batch && jdbcResult != null) {
                throw new IllegalArgumentException("jdbcResult may not be supplied when a batch execution has been requested");
            }
            if (statement instanceof PreparedStatement ps) {
                // PreparedStatement or CallableStatement
                if (sql != null) {
                    throw new IllegalArgumentException("sql cannot be supplied with a PreparedStatement");
                }
                this.sql = null;
                if (generatedKeysBehavior != null && generatedKeysBehavior != GeneratedKeysBehavior.NONE) {
                    throw new IllegalArgumentException("generatedKeysBehavior cannot be supplied with a PreparedStatement");
                }
                this.generatedKeysBehavior = GeneratedKeysBehavior.NONE; // really is just irrelevant
                if (columnIndices != null && columnIndices.length > 0) {
                    throw new IllegalArgumentException("columnIndices cannot be supplied with a PreparedStatement");
                }
                this.columnIndices = EMPTY_INT_ARRAY;
                if (columnNames != null && columnNames.length > 0) {
                    throw new IllegalArgumentException("columnNames cannot be supplied with a PreparedStatement");
                }
                this.columnNames = EMPTY_STRING_ARRAY;
                if (outParameterIndices.length == 0) {
                    this.outParameterIndices = EMPTY_INT_ARRAY;
                } else if (batch) {
                    throw new IllegalArgumentException("outParameterIndices may not be supplied when"
                                                       + " a batch execution has been requested");
                } else if (ps instanceof CallableStatement) {
                    this.outParameterIndices = outParameterIndices.clone();
                } else {
                    throw new IllegalArgumentException("outParameterIndices may be supplied only for a CallableStatement");
                }
            } else {
                // Plain Statement
                if (jdbcResult != null) {
                    if (sql != null) {
                        throw new IllegalArgumentException("sql may not be supplied when"
                                                           + " the supplied Statement has already been executed");
                    }
                    this.sql = null;
                } else if (batch) {
                    if (sql != null) {
                        throw new IllegalArgumentException("sql may not be supplied when"
                                                           + " a batch execution has been requested");
                    }
                    this.sql = null;
                } else if (sql == null) {
                    throw new IllegalArgumentException("sql must be supplied with non-PreparedStatements",
                                                       new NullPointerException("sql"));
                } else {
                    this.sql = sql;
                }
                if (columnIndices.length == 0) {
                    this.columnIndices = EMPTY_INT_ARRAY;
                } else if (batch) {
                    throw new IllegalArgumentException("columnIndices may not be supplied when"
                                                       + " a batch execution has been requested");
                } else {
                    this.columnIndices = columnIndices.clone();
                }
                if (columnNames.length == 0) {
                    this.columnNames = EMPTY_STRING_ARRAY;
                } else if (batch) {
                    throw new IllegalArgumentException("columnNames may not be supplied when"
                                                       + " a batch execution has been requested");
                } else if (this.columnIndices.length > 0) {
                    throw new IllegalArgumentException("columnIndices and columnNames may not be supplied together");
                } else {
                    this.columnNames = columnNames.clone();
                }
                this.generatedKeysBehavior = (this.columnIndices.length > 0 || this.columnNames.length > 0)
                    ? GeneratedKeysBehavior.RETURN
                    : generatedKeysBehavior;
                if (outParameterIndices.length > 0) {
                    throw new IllegalArgumentException("outParameterIndices may be supplied only for a CallableStatement");
                }
                this.outParameterIndices = EMPTY_INT_ARRAY;
            }
            this.batch = batch;
            this.jdbcResult = jdbcResult;
            this.resultsAdvancementBehavior =
                resultsAdvancementBehavior == null ? ResultsAdvancementBehavior.CLOSE_CURRENT_RESULT : resultsAdvancementBehavior;
        }

        Statement statement() {
            return this.statement;
        }

        boolean batch() {
            return this.batch;
        }

        Optional<String> sql() {
            return Optional.ofNullable(this.sql);
        }

        GeneratedKeysBehavior generatedKeysBehavior() {
            return this.generatedKeysBehavior;
        }

        int[] columnIndices() {
            return this.columnIndices;
        }

        String[] columnNames() {
            return this.columnNames;
        }

        Optional<JdbcResult> initialResult() {
            return Optional.ofNullable(this.jdbcResult);
        }

        ResultsAdvancementBehavior resultsAdvancementBehavior() {
            return this.resultsAdvancementBehavior;
        }

        int[] outParameterIndices() {
            return this.outParameterIndices;
        }

    }

}
