/*
 * Copyright (c) 2026 Oracle and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.helidon.data.jdbc;

import java.sql.CallableStatement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Optional;
import java.util.Spliterator;
import java.util.function.Consumer;
import java.util.stream.Stream;
import java.util.stream.StreamSupport;

import io.helidon.data.jdbc.function.JdbcConsumer;
import io.helidon.data.jdbc.function.JdbcFunction;
import io.helidon.data.jdbc.function.JdbcRunnable;

import static io.helidon.data.jdbc.function.JdbcRunnable.runnable;
import static java.sql.Statement.CLOSE_CURRENT_RESULT;

/**
 * An object representing the family of results any {@link Statement} {@linkplain Statement#execute(String) execution},
 * or {@link java.sql.PreparedStatement} {@linkplain java.sql.PreparedStatement#execute() execution (including
 * <code>CallableStatement</code> execution)}, may produce.
 *
 * <p>As with all constructs related to JDBC, a {@link JdbcResults} is not necessarily safe for concurrent use by
 * multiple threads unless explicitly noted.</p>
 *
 * @see #advance()
 * @see #get()
 * @see JdbcResult
 */
public interface JdbcResults extends JdbcOpen, JdbcWarningsBearing {

    /**
     * Advances to the next {@link JdbcResult} in the notional chain of results and returns {@code true} if and only if
     * there is one.
     *
     * <p>A {@link JdbcResults} is notionally positioned <em>before</em> the notional first result. If {@link
     * #advance()} is never called, {@link #get()} will always return an {@linkplain Optional#isEmpty() empty} {@link
     * Optional}.</p>
     *
     * <p>If this method returns {@code true}, then the {@link Optional} returned by {@link #get()} will be {@linkplain
     * Optional#isPresent() present}.</p>
     *
     * @return {@code true} if and only if advancement was successful
     * @throws IllegalStateException if this {@link JdbcResults} is {@linkplain #close() closed}
     * @throws SQLException if a database error occurs
     * @see #get()
     */
    boolean advance() throws SQLException;

    /**
     * Returns {@code true} if and only if this {@link JdbcResults} is {@linkplain #close() closed}.
     *
     * <p>This operation is idempotent.</p>
     *
     * @return {@code true} if and only if this {@link JdbcResults} is {@linkplain #close() closed}.
     * @throws SQLException if a database error occurs
     * @see #close()
     */
    boolean closed() throws SQLException;

    /**
     * Returns the current {@link JdbcResult} if {@link #advance()} has been called and there is one.
     *
     * <p>If this method returns an {@linkplain Optional#isEmpty() empty} {@link Optional}, then either {@link
     * #advance()} has not yet been called, or an invocation of {@link #advance()} returned {@code false}.</p>
     *
     * @return a non-{@code null} {@link Optional} containing the current {@link JdbcResult} if there is one
     * @throws IllegalStateException if this {@link JdbcResults} is {@linkplain #close() closed}
     * @throws SQLException if a database error occurs
     * @see #advance()
     * @see JdbcResult
     */
    Optional<JdbcResult> get() throws SQLException;

    /**
     * Returns any keys generated by the statement execution.
     *
     * @return a non-{@code null} {@link Optional} containing any keys generated by the statement execution
     * @throws IllegalStateException if this {@link JdbcResults} is {@linkplain #close() closed}
     * @throws SQLException if a database error occurs
     * @see Statement#getGeneratedKeys()
     */
    Optional<ResultSet> keys() throws SQLException;

    @Override // JdbcOpen
    JdbcResults onClose(JdbcRunnable closeAction) throws SQLException;

    /**
     * A convenience method that performs an action for each remaining {@link JdbcResult}.
     *
     * @param c a non-{@code null} {@link JdbcConsumer} accepting a {@link JdbcResult}
     * @throws NullPointerException if {@code c} is {@code null}
     * @throws IllegalStateException if this {@link JdbcResults} is {@linkplain #closed() closed}
     * @throws SQLException if a database error occurs
     */
    default void forEachRemaining(JdbcConsumer<? super JdbcResult> c) throws SQLException {
        while (this.advance()) {
            // If advance returns true, get() returns a present Optional
            c.accept(this.get().orElseThrow(AssertionError::new));
        }
    }

    /**
     * A convenience method thta performs an action for each remaining {@link JdbcResult} of a particular type.
     *
     * @param <JR> a {@link JdbcResult} subtype
     * @param type a non-{@code null} {@link Class} identifying a {@link JdbcResult} subtype
     * @param c a non-{@code null} {@link JdbcConsumer} accepting a specific type of {@link JdbcResult}
     * @throws NullPointerException if any argument is {@code null}
     * @throws IllegalStateException if a {@link JdbcResult} not of the appropriate type is encountered, or if this
     * {@link JdbcResults} is {@linkplain #closed() closed}
     * @throws SQLException if a database error occurs
     */
    default <JR extends JdbcResult> void forEachRemaining(Class<JR> type, JdbcConsumer<? super JR> c) throws SQLException {
        while (this.advance()) {
            JdbcResult result = this.get().orElse(null);
            if (!type.isInstance(result)) {
                throw new IllegalStateException("Expected " + type.getSimpleName()
                                                + ", got " + (result == null ? "no result" : result.getClass().getSimpleName()));
            }
            c.accept(type.cast(result));
        }
    }

    /**
     * A convenience method that adapts the supplied {@link JdbcConsumer} to a void-returning {@link JdbcFunction} and
     * calls the {@link #mapNext(Class, JdbcFunction)} with the supplied {@link Class} and the adapted {@link
     * JdbcConsumer}.
     *
     * @param <JR> a {@link JdbcResult} subtype
     * @param type a non-{@code null} {@link Class} identifying a {@link JdbcResult} subtype
     * @param c a non-{@code null} {@link JdbcConsumer} accepting a specific type of {@link JdbcResult}
     * @throws NullPointerException if any argument is {@code null}
     * @throws IllegalStateException if there is not a next {@link JdbcResult} of the appropriate type remaining, or if
     * this {@link JdbcResults} is {@linkplain #closed() closed}
     * @throws SQLException if a database error occurs
     * @see #mapNext(Class, JdbcFunction)
     */
    default <JR extends JdbcResult> void forNext(Class<JR> type, JdbcConsumer<? super JR> c) throws SQLException {
        this.mapNext(type, jr -> {
                c.accept(jr);
                return null;
            });
    }

    /**
     * A convenience method that adapts the supplied {@link JdbcConsumer} to a void-returning {@link JdbcFunction} and
     * calls the {@link #mapOnlyRemaining(Class, JdbcFunction)} with the supplied {@link Class} and the adapted {@link
     * JdbcConsumer}.
     *
     * <p><strong>This method (indirectly) attempts another {@linkplain #advance() advancement}</strong> and throws an
     * {@link IllegalStateException} if it is successful.</p>
     *
     * @param <JR> a {@link JdbcResult} subtype
     * @param type a non-{@code null} {@link Class} identifying a {@link JdbcResult} subtype
     * @param c a non-{@code null} {@link JdbcConsumer} accepting a specific type of {@link JdbcResult}
     * @throws NullPointerException if any argument is {@code null}
     * @throws IllegalStateException if there is not exactly one {@link JdbcResult} of the appropriate type remaining,
     * or if this {@link JdbcResults} is {@linkplain #closed() closed}
     * @throws SQLException if a database error occurs
     * @see #mapOnlyRemaining(Class, JdbcFunction)
     */
    default <JR extends JdbcResult> void forOnlyRemaining(Class<JR> type, JdbcConsumer<? super JR> c) throws SQLException {
        this.mapOnlyRemaining(type, jr -> {
                c.accept(jr);
                return null;
            });
    }

    /**
     * A convenience method that {@linkplain #advance() advances} this {@link JdbcResult}, and, assuming it is
     * successful, {@linkplain #get() gets the current result}, and, assuming it the proper {@link JdbcResult} subtype,
     * passes it to the supplied mapping function and returns the result.
     *
     * @param <JR> a {@link JdbcResult} subtype
     * @param <R> the mapped type
     * @param type a non-{@code null} {@link Class} identifying a {@link JdbcResult} subtype
     * @param f a non-{@code null} {@link JdbcFunction} accepting a specific type of {@link JdbcResult} responsible for
     * mapping it
     * @return the mapping result
     * @throws NullPointerException if any argument is {@code null}
     * @throws IllegalStateException if there is not a next {@link JdbcResult} of the appropriate type remaining, or if
     * this {@link JdbcResults} is {@linkplain #closed() closed}
     * @throws SQLException if a database error occurs
     */
    default <JR extends JdbcResult, R> R mapNext(Class<JR> type, JdbcFunction<? super JR, ? extends R> f) throws SQLException {
        if (!this.advance()) {
            throw new IllegalStateException("Expected at least one " + type.getSimpleName() + ", but there were no results");
        }
        JdbcResult result = this.get().orElse(null);
        if (!type.isInstance(result)) {
            throw new IllegalStateException("Expected at least one " + type.getSimpleName()
                                            + ", got " + (result == null ? "no result" : result.getClass().getSimpleName()));
        }
        return f.apply(type.cast(result));
    }

    /**
     * A convenience method that calls the {@link #mapNext(Class, JdbcFunction)} method with the supplied arguments,
     * presuming that the resulting {@linkplain #advance() advancement} will be the last one, and returns the return
     * value.
     *
     * <p><strong>This method attempts another {@linkplain #advance() advancement}</strong> and throws an {@link
     * IllegalStateException} if it is successful.</p>
     *
     * @param <JR> a {@link JdbcResult} subtype
     * @param <R> the mapped type
     * @param type a non-{@code null} {@link Class} identifying a {@link JdbcResult} subtype
     * @param f a non-{@code null} {@link JdbcFunction} accepting a specific type of {@link JdbcResult} responsible for
     * mapping it
     * @return the mapping result
     * @throws NullPointerException if any argument is {@code null}
     * @throws IllegalStateException if there is not exactly one {@link JdbcResult} of the appropriate type remaining,
     * or if this {@link JdbcResults} is {@linkplain #closed() closed}
     * @throws SQLException if a database error occurs
     * @see #mapNext(Class, JdbcFunction)
     */
    default <JR extends JdbcResult, R> R mapOnlyRemaining(Class<JR> type, JdbcFunction<? super JR, ? extends R> f)
        throws SQLException {
        R returnValue = this.mapNext(type, f);
        if (this.advance()) {
            throw new IllegalStateException("Expected exactly one " + type.getSimpleName()
                                            + ", but there were additional results");
        }
        return returnValue;
    }

    /**
     * Returns a new {@link Spliterator Spliterator&lt;JdbcResult&gt;}.
     *
     * <p>The returned {@link Spliterator} may throw {@link UncheckedSQLException}s in addition to any other exceptions
     * it may throw.</p>
     *
     * @return a new {@link Spliterator Spliterator&lt;JdbcResult&gt;}
     * @see Spliterator
     * @see UncheckedSQLException
     */
    default Spliterator<JdbcResult> spliterator() {
        return new Spliterator<>() {
            @Override // Spliterator<JdbcResult>
            public Spliterator<JdbcResult> trySplit() {
                return null; // cannot be parallel
            }
            @Override // Spliterator<JdbcResult>
            public long estimateSize() {
                return Long.MAX_VALUE; // unknown
            }
            @Override // Spliterator<JdbcResult>
            public int characteristics() {
                return ORDERED | NONNULL;
            }
            @Override // Spliterator<JdbcResult>
            public void forEachRemaining(Consumer<? super JdbcResult> action) {
                try {
                    JdbcResults.this.<JdbcResult>forEachRemaining(JdbcResult.class, action::accept);
                } catch (SQLException e) {
                    throw new UncheckedSQLException(e);
                }
            }
            @Override // Spliterator<JdbcResult>
            public boolean tryAdvance(Consumer<? super JdbcResult> action) {
                try {
                    if (JdbcResults.this.advance()) {
                        action.accept(JdbcResults.this.get().orElseThrow(AssertionError::new));
                        return true;
                    } else {
                        return false;
                    }
                } catch (SQLException e) {
                    throw new UncheckedSQLException(e);
                }
            }
        };
    }

    /**
     * Returns a non-{@code null}, sequential {@link Stream Stream&lt;JdbcResult&gt;} of this {@link JdbcResults}'
     * contents.
     *
     * <p>When the returned {@link Stream} is {@linkplain Stream#close() closed}, this {@link JdbcResults} will be
     * {@linkplain #close() closed}.</p>
     *
     * @return a non-{@code null} {@link Stream}
     * @see #close()
     * @see #spliterator()
     * @see StreamSupport#stream(Spliterator, boolean)
     * @see Stream#onClose(Runnable)
     * @see Stream#close()
     */
    default Stream<JdbcResult> stream() {
        return StreamSupport.stream(this.spliterator(), false /* deliberately not parallel */).onClose(runnable(this::close));
    }


    /*
     * Static methods.
     */


    /**
     * Returns a new {@link JdbcResults} representing the potentially many results produced by the execution of the
     * supplied {@link CallableStatement}.
     *
     * @param cs a non-{@link CallableStatement}
     * @param outParameterIndices a non-{@code null} array of {@code 1}-based already registered {@code OUT} parameters
     * in the supplied {@link CallableStatement}
     * @return a new {@link JdbcResult}; callers are responsible for {@linkplain #close() closing it}
     * @throws NullPointerException if any argument is {@code null}
     * @see #of(CallableStatement, int, int[])
     * @see CallableStatement
     * @see PreparedStatement#execute()
     */
    static JdbcResults of(CallableStatement cs, int[] outParameterIndices) {
        return of(cs,
                  CLOSE_CURRENT_RESULT,
                  outParameterIndices);
    }

    /**
     * Returns a new {@link JdbcResults} representing the potentially many results produced by the execution of the
     * supplied {@link CallableStatement}.
     *
     * @param cs a non-{@link CallableStatement}
     * @param current a constant as must be supplied to invocations of {@link Statement#getMoreResults(int)}
     * @param outParameterIndices a non-{@code null} array of {@code 1}-based already registered {@code OUT} parameters
     * in the supplied {@link CallableStatement}
     * @return a new {@link JdbcResult}; callers are responsible for {@linkplain #close() closing it}
     * @throws NullPointerException if any argument is {@code null}
     * @see CallableStatement
     * @see PreparedStatement#execute()
     * @see Statement#getMoreResults(int)
     * @see Statement#CLOSE_ALL_RESULTS
     * @see Statement#CLOSE_CURRENT_RESULT
     * @see Statement#KEEP_CURRENT_RESULT
     */
    static JdbcResults of(CallableStatement cs, int current, int[] outParameterIndices) {
        return new JdbcResultsImpl(cs,
                                   () -> cs.getMoreResults(current),
                                   outParameterIndices);
    }

    /**
     * Returns a new {@link JdbcResults} representing the potentially many results produced by the execution of the
     * supplied {@link PreparedStatement}.
     *
     * @param ps a non-{@link PreparedStatement}
     * @return a new {@link JdbcResult}; callers are responsible for {@linkplain #close() closing it}
     * @throws NullPointerException if any argument is {@code null}
     * @see PreparedStatement#execute()
     * @see Statement#getMoreResults()
     */
    static JdbcResults of(PreparedStatement ps) {
        return new JdbcResultsImpl(ps,
                                   ps::getMoreResults);
    }

    /**
     * Returns a new {@link JdbcResults} representing the potentially many results produced by the execution of the
     * supplied {@link PreparedStatement}.
     *
     * @param ps a non-{@link PreparedStatement}
     * @param current a constant as must be supplied to invocations of {@link Statement#getMoreResults(int)}
     * @return a new {@link JdbcResult}; callers are responsible for {@linkplain #close() closing it}
     * @throws NullPointerException if any argument is {@code null}
     * @see PreparedStatement#execute()
     * @see Statement#getMoreResults(int)
     * @see Statement#CLOSE_ALL_RESULTS
     * @see Statement#CLOSE_CURRENT_RESULT
     * @see Statement#KEEP_CURRENT_RESULT
     */
    static JdbcResults of(PreparedStatement ps, int current) {
        return new JdbcResultsImpl(ps,
                                   () -> ps.getMoreResults(current));
    }

    /**
     * Returns a new {@link JdbcResults} representing the potentially many results produced by the execution of the
     * supplied {@link Statement}.
     *
     * @param s a non-{@code null} {@link Statement}
     * @param sql the non-{@code null} {@code SQL} statement to execute
     * @return a new {@link JdbcResult}; callers are responsible for {@linkplain #close() closing it}
     * @throws NullPointerException if any argument is {@code null}
     * @see Statement#execute(String)
     * @see Statement#getMoreResults()
     * @deprecated While this method is supported, its use is discouraged, since it cannot be proven that {@code sql} is
     * safe
     */
    @Deprecated
    static JdbcResults of(Statement s, String sql) {
        return new JdbcResultsImpl(s,
                                   () -> s.execute(sql),
                                   s::getMoreResults);
    }

    /**
     * Returns a new {@link JdbcResults} representing the potentially many results produced by the execution of the
     * supplied {@link Statement}.
     *
     * @param s a non-{@code null} {@link Statement}
     * @param sql the non-{@code null} {@code SQL} statement to execute
     * @param autoGeneratedKeys a constant indicating whether auto-generated keys should be made available for retrieval
     * using the method {@link Statement#getGeneratedKeys()}; one of the following constants: {@link
     * Statement#RETURN_GENERATED_KEYS} or {@link Statement#NO_GENERATED_KEYS}
     * @return a new {@link JdbcResult}; callers are responsible for {@linkplain #close() closing it}
     * @throws NullPointerException if any argument is {@code null}
     * @see Statement#execute(String, int)
     * @see Statement#getMoreResults()
     * @deprecated While this method is supported, its use is discouraged, since it cannot be proven that {@code sql} is
     * safe
     */
    @Deprecated
    static JdbcResults of(Statement s, String sql, int autoGeneratedKeys) {
        return new JdbcResultsImpl(s,
                                   () -> s.execute(sql, autoGeneratedKeys),
                                   s::getMoreResults);
    }

    /**
     * Returns a new {@link JdbcResults} representing the potentially many results produced by the execution of the
     * supplied {@link Statement}.
     *
     * @param s a non-{@code null} {@link Statement}
     * @param sql the non-{@code null} {@code SQL} statement to execute
     * @param autoGeneratedKeys a constant indicating whether auto-generated keys should be made available for retrieval
     * using the method {@link Statement#getGeneratedKeys()}; one of the following constants: {@link
     * Statement#RETURN_GENERATED_KEYS} or {@link Statement#NO_GENERATED_KEYS}
     * @param current a constant as must be supplied to invocations of {@link Statement#getMoreResults(int)}
     * @return a new {@link JdbcResult}; callers are responsible for {@linkplain #close() closing it}
     * @throws NullPointerException if any argument is {@code null}
     * @see Statement#execute(String, int)
     * @see Statement#getMoreResults(int)
     * @see Statement#CLOSE_ALL_RESULTS
     * @see Statement#CLOSE_CURRENT_RESULT
     * @see Statement#KEEP_CURRENT_RESULT
     * @deprecated While this method is supported, its use is discouraged, since it cannot be proven that {@code sql} is
     * safe
     */
    @Deprecated
    static JdbcResults of(Statement s, String sql, int autoGeneratedKeys, int current) {
        return new JdbcResultsImpl(s,
                                   () -> s.execute(sql, autoGeneratedKeys),
                                   () -> s.getMoreResults(current));
    }

    /**
     * Returns a new {@link JdbcResults} representing the potentially many results produced by the execution of the
     * supplied {@link Statement}.
     *
     * @param s a non-{@code null} {@link Statement}
     * @param sql the non-{@code null} {@code SQL} statement to execute
     * @param columnIndexes an array of the indexes of the columns in the inserted row that should be made available for
     * retrieval by a call to the method {@link Statement#getGeneratedKeys()}
     * @param current a constant as must be supplied to invocations of {@link Statement#getMoreResults(int)}
     * @return a new {@link JdbcResult}; callers are responsible for {@linkplain #close() closing it}
     * @throws NullPointerException if any argument is {@code null}
     * @see Statement#execute(String, int[])
     * @see Statement#getMoreResults(int)
     * @see Statement#CLOSE_ALL_RESULTS
     * @see Statement#CLOSE_CURRENT_RESULT
     * @see Statement#KEEP_CURRENT_RESULT
     * @deprecated While this method is supported, its use is discouraged, since it cannot be proven that {@code sql} is
     * safe
     */
    @Deprecated
    static JdbcResults of(Statement s, String sql, int[] columnIndexes, int current) {
        return new JdbcResultsImpl(s,
                                   () -> s.execute(sql, columnIndexes),
                                   () -> s.getMoreResults(current));
    }

    /**
     * Returns a new {@link JdbcResults} representing the potentially many results produced by the execution of the
     * supplied {@link Statement}.
     *
     * @param s a non-{@code null} {@link Statement}
     * @param sql the non-{@code null} {@code SQL} statement to execute
     * @param columnNames an array of the names of the columns in the inserted row that should be made available for
     * retrieval by a call to the method {@link Statement#getGeneratedKeys()}
     * @param current a constant as must be supplied to invocations of {@link Statement#getMoreResults(int)}
     * @return a new {@link JdbcResult}; callers are responsible for {@linkplain #close() closing it}
     * @throws NullPointerException if any argument is {@code null}
     * @see Statement#execute(String, String[])
     * @see Statement#getMoreResults(int)
     * @see Statement#CLOSE_ALL_RESULTS
     * @see Statement#CLOSE_CURRENT_RESULT
     * @see Statement#KEEP_CURRENT_RESULT
     * @deprecated While this method is supported, its use is discouraged, since it cannot be proven that {@code sql} is
     * safe
     */
    @Deprecated
    static JdbcResults of(Statement s, String sql, String[] columnNames, int current) {
        return new JdbcResultsImpl(s,
                                   () -> s.execute(sql, columnNames),
                                   () -> s.getMoreResults(current));
    }

}
