/*
 * Copyright (c) 2026 Oracle and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.helidon.data.jdbc;

import java.lang.annotation.ElementType;
import java.lang.annotation.Repeatable;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Annotations that describe SQL executed by a Helidon Data JDBC repository.
 * <p>
 * These annotations contain JDBC-specific repository metadata. Provider-neutral repository annotations, such as
 * {@code Data.Repository} and {@code Data.PersistenceUnit}, remain in {@code io.helidon.data.Data}.
 */
public final class Jdbc {

    /**
     * Sentinel used when an input parameter lets the JDBC driver infer its SQL type.
     */
    public static final int INFERRED_TYPE = Integer.MIN_VALUE;

    private Jdbc() {
        throw new UnsupportedOperationException("No instances of Jdbc are allowed");
    }

    /**
     * Declares the SQL statement for a JDBC repository method.
     * <p>
     * The JDBC provider rewrites supported named parameters during code generation and emits positional JDBC binds.
     * The annotation does not itself determine how JDBC executes the statement. Use {@link Execution} when the method
     * signature does not identify an unambiguous execution type.
     */
    @Target(ElementType.METHOD)
    @Retention(RetentionPolicy.SOURCE)
    public @interface Statement {
        /**
         * SQL statement.
         *
         * @return SQL statement
         */
        String value();
    }

    /**
     * Explicitly selects how the JDBC provider executes a repository method's {@link Statement}.
     * <p>
     * This annotation is optional when the method signature and other JDBC annotations identify exactly one execution
     * type. Code generation rejects an ambiguous method instead of inspecting SQL text or guessing at runtime.
     */
    @Target(ElementType.METHOD)
    @Retention(RetentionPolicy.SOURCE)
    public @interface Execution {
        /**
         * Execution type.
         *
         * @return execution type
         */
        ExecutionType value();
    }

    /**
     * Supported JDBC repository execution types.
     */
    public enum ExecutionType {
        /**
         * Executes the statement as a query and maps its result rows.
         */
        QUERY,

        /**
         * Executes the statement as an update and returns no value or an update count, unless {@link GeneratedKeys}
         * requests generated values.
         */
        UPDATE,

        /**
         * Invokes a stored procedure or function through a JDBC callable statement.
         */
        CALL
    }

    /**
     * Requests values generated by an update statement.
     * <p>
     * An empty value requests the JDBC driver's default generated-key result. Otherwise, the values name generated
     * columns in result order. This annotation implies {@link ExecutionType#UPDATE} when {@link Execution} is absent.
     */
    @Target(ElementType.METHOD)
    @Retention(RetentionPolicy.SOURCE)
    public @interface GeneratedKeys {
        /**
         * Generated columns to request.
         *
         * @return generated column names, or an empty array for driver-default generated keys
         */
        String[] value() default {};
    }

    /**
     * Requests generation of an identity-based row reducer for a joined record projection.
     * <p>
     * SQL column labels define record-component paths. Identity paths identify the logical root and every collection
     * element scope, allowing generated code to combine repeated physical rows without reflection or database metadata.
     * All identity paths in one scope form an ordered composite identity.
     * <p>
     * The generated reducer preserves first-seen SQL order, suppresses duplicate objects within their parent, and treats
     * a completely null child identity as an absent outer-join child. The root and all collection element types must be
     * records. This annotation cannot be combined with {@link RowMapper}, {@link RowReducer}, generated keys, or query
     * traversal requests.
     */
    @Target(ElementType.METHOD)
    @Retention(RetentionPolicy.SOURCE)
    public @interface IdentityReducer {
        /**
         * Root-relative record-component paths that identify the root and every collection element scope.
         *
         * @return identity component paths
         */
        String[] identityPaths();
    }

    /**
     * Selects an application-provided {@link JdbcClient.RowMapper} service for one physical result row.
     * <p>
     * With a mapper class, generated code injects that exact service type. Without a class, generated code requires a
     * row-mapper service whose generic result type exactly matches the mapped repository type. If this annotation is
     * absent and direct record mapping is available, the generated repository may use an optional matching mapper
     * service and fall back to its generated mapper.
     * <p>
     * A mapper service used by a singleton repository must be stateless or thread-safe. The mapper receives a scoped
     * {@link JdbcClient.Row} and never owns JDBC resources. This annotation cannot be combined with
     * {@link IdentityReducer} or {@link RowReducer}.
     */
    @Target(ElementType.METHOD)
    @Retention(RetentionPolicy.SOURCE)
    public @interface RowMapper {
        /**
         * Concrete mapper service type, or {@link Void} to select a mapper by its generic result type.
         *
         * @return mapper service type
         */
        Class<?> value() default Void.class;
    }

    /**
     * Selects an application-provided {@link JdbcClient.RowReducer} for multi-row aggregation.
     * <p>
     * The reducer result type must exactly match the repository method return type. The reducer must be a concrete type
     * with an accessible no-argument constructor. Generated code creates a new reducer for each invocation, and the JDBC
     * provider retains ownership of every JDBC resource.
     */
    @Target(ElementType.METHOD)
    @Retention(RetentionPolicy.SOURCE)
    public @interface RowReducer {
        /**
         * Reducer implementation selected for the repository method.
         *
         * @return reducer implementation type
         */
        Class<?> value();
    }

    /**
     * Declares a stored-procedure or function input parameter.
     * <p>
     * A name locates a unique named marker at code generation. An index locates a positional marker. When both are
     * present, they must identify the same one-based JDBC position. The annotated repository parameter supplies the
     * non-null input value.
     */
    @Target(ElementType.PARAMETER)
    @Retention(RetentionPolicy.SOURCE)
    public @interface InParameter {
        /**
         * Named marker and logical parameter name.
         *
         * @return marker name, or an empty string when {@link #index()} is used
         */
        String name() default "";

        /**
         * One-based JDBC parameter position.
         *
         * @return JDBC position, or {@code -1} when {@link #name()} locates the parameter
         */
        int index() default -1;

        /**
         * JDBC type code used for input binding.
         *
         * @return a {@link java.sql.Types} or vendor type code, or {@link Jdbc#INFERRED_TYPE}
         */
        int jdbcType() default INFERRED_TYPE;
    }

    /**
     * Declares a stored-procedure or function input/output parameter.
     * <p>
     * The annotated repository parameter supplies the non-null input value and its declared Java type defines the
     * output type. The generated repository binds and registers the same physical JDBC position.
     */
    @Target(ElementType.PARAMETER)
    @Retention(RetentionPolicy.SOURCE)
    public @interface InOutParameter {
        /**
         * Named marker and logical output name.
         *
         * @return marker and output name, or an empty string when {@link #index()} is used
         */
        String name() default "";

        /**
         * One-based JDBC parameter position.
         *
         * @return JDBC position, or {@code -1} when {@link #name()} locates the parameter
         */
        int index() default -1;

        /**
         * JDBC type code used for input binding and output registration.
         *
         * @return a {@link java.sql.Types} or vendor type code
         */
        int jdbcType();
    }

    /**
     * Declares a stored-procedure output parameter.
     * <p>
     * Scalar outputs declare a supported {@link #javaType()}. A cursor output uses {@link java.sql.Types#REF_CURSOR}
     * and leaves {@code javaType} as {@link Void}. Output values are available only through the callback-scoped call
     * output view.
     */
    @Target(ElementType.METHOD)
    @Retention(RetentionPolicy.SOURCE)
    @Repeatable(OutParameters.class)
    public @interface OutParameter {
        /**
         * Logical output name and, for named SQL, marker name.
         *
         * @return non-blank output name
         */
        String name();

        /**
         * One-based JDBC parameter position.
         *
         * @return JDBC position, or {@code -1} when {@link #name()} locates the parameter
         */
        int index() default -1;

        /**
         * JDBC type code used for output registration.
         *
         * @return a {@link java.sql.Types} or vendor type code
         */
        int jdbcType();

        /**
         * Supported Java type for a scalar output.
         *
         * @return scalar Java type, or {@link Void} for a cursor output
         */
        Class<?> javaType() default Void.class;

        /**
         * Optional database type name used by JDBC output registration.
         *
         * @return database type name, or an empty string for ordinary registration
         */
        String typeName() default "";
    }

    /**
     * Java repeatable-annotation container for {@link OutParameter}.
     * <p>
     * Applications normally repeat {@code @Jdbc.OutParameter}; they do not use this container directly.
     */
    @Target(ElementType.METHOD)
    @Retention(RetentionPolicy.SOURCE)
    public @interface OutParameters {
        /**
         * Output declarations.
         *
         * @return output declarations
         */
        OutParameter[] value();
    }

    /**
     * Declares the return value of a JDBC function.
     * <p>
     * A function return always occupies JDBC position {@code 1}; its position is deliberately not configurable.
     */
    @Target(ElementType.METHOD)
    @Retention(RetentionPolicy.SOURCE)
    public @interface ReturnParameter {
        /**
         * Named return marker and logical output name.
         *
         * @return non-blank return name
         */
        String name();

        /**
         * JDBC type code used for output registration.
         *
         * @return a {@link java.sql.Types} or vendor type code
         */
        int jdbcType();

        /**
         * Supported Java return type.
         *
         * @return Java return type
         */
        Class<?> javaType();

        /**
         * Optional database type name used by JDBC output registration.
         *
         * @return database type name, or an empty string for ordinary registration
         */
        String typeName() default "";
    }
}
