/*
 * Copyright (c) 2026 Oracle and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.helidon.data.jdbc;

import java.lang.annotation.ElementType;
import java.lang.annotation.Repeatable;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;
import java.sql.JDBCType;

/**
 * Annotations that describe SQL executed by a Helidon Data JDBC repository.
 * <p>
 * These annotations contain JDBC-specific repository metadata. Provider-neutral repository annotations, such as
 * {@code Data.Repository} and {@code Data.PersistenceUnit}, remain in {@code io.helidon.data.Data}.
 */
public final class Jdbc {

    /**
     * Sentinel used when an input parameter lets the JDBC driver infer its SQL type.
     */
    static final int INFERRED_TYPE = Integer.MIN_VALUE;

    private Jdbc() {
        throw new UnsupportedOperationException("No instances of Jdbc are allowed");
    }

    /**
     * Declares the SQL statement for a JDBC repository method.
     * <p>
     * For query and update execution, every {@code :name} marker must match an ordinary Java method parameter and may
     * occur more than once. The JDBC provider rewrites those markers during code generation and emits positional JDBC
     * binds; the marker names are never sent to the driver. Call execution requires standard JDBC procedure or function
     * escape syntax and may use either named provider markers or positional {@code ?} markers, but not both. This
     * annotation does not itself determine how JDBC executes the statement. Use {@link Execution} when the method
     * signature does not identify an unambiguous execution type.
     */
    @Target(ElementType.METHOD)
    @Retention(RetentionPolicy.SOURCE)
    public @interface Statement {
        /**
         * SQL statement.
         *
         * @return SQL statement
         */
        String value();
    }

    /**
     * Explicitly selects how the JDBC provider executes a repository method's {@link Statement}.
     * <p>
     * This annotation is optional when the method signature and other JDBC annotations identify exactly one execution
     * type. Primitive {@code int} and {@code long} returns are ambiguous between scalar queries and update counts. A
     * zero-parameter procedure with no callable annotation also requires explicit {@link ExecutionType#CALL}. Code
     * generation rejects an ambiguous method instead of inspecting SQL text or guessing at runtime.
     */
    @Target(ElementType.METHOD)
    @Retention(RetentionPolicy.SOURCE)
    public @interface Execution {
        /**
         * Execution type.
         *
         * @return execution type
         */
        ExecutionType value();
    }

    /**
     * Supported JDBC repository execution types.
     */
    public enum ExecutionType {
        /**
         * Executes the statement as a query and maps its result rows.
         */
        QUERY,

        /**
         * Executes the statement as an update and returns no value or an update count, unless {@link GeneratedKeys}
         * requests generated values.
         */
        UPDATE,

        /**
         * Invokes a stored procedure or function through a JDBC callable statement.
         */
        CALL
    }

    /**
     * Kind of value exposed by an output parameter or function return.
     * <p>
     * The kind is distinct from the JDBC type code used to register the output. In particular, a driver may require a
     * vendor-specific type code for a cursor instead of {@link java.sql.Types#REF_CURSOR}.
     */
    public enum OutputKind {
        /**
         * Scalar value read directly through JDBC and eligible for detached return mode.
         */
        SCALAR,

        /**
         * Callback-scoped cursor whose rows must be consumed before the callable statement closes.
         */
        CURSOR
    }

    /**
     * Requests values generated by an update statement.
     * <p>
     * An empty value requests the JDBC driver's default generated-key result. Otherwise, the values name generated
     * columns in result order. A scalar result can use the driver-default first key column. Generated record mapping
     * requires named columns that match its components; an explicit {@link RowMapper} can instead handle driver-specific
     * key layouts. This annotation implies {@link ExecutionType#UPDATE} when {@link Execution} is absent.
     */
    @Target(ElementType.METHOD)
    @Retention(RetentionPolicy.SOURCE)
    public @interface GeneratedKeys {
        /**
         * Generated columns to request.
         *
         * @return generated column names, or an empty array for driver-default generated keys
         */
        String[] value() default {};
    }

    /**
     * Requests generation of an identity-based row reducer for a joined record projection.
     * <p>
     * SQL column labels must exactly define root-relative record-component paths. Identity paths identify the logical root
     * and every collection element scope, allowing generated code to combine repeated physical rows without reflection or
     * database metadata. Every record scope requires an identity; all identity paths in one scope form an ordered
     * composite identity.
     * <p>
     * The generated reducer preserves first-seen SQL order, suppresses duplicate objects within their parent, and treats
     * a completely null child identity as an absent outer-join child. A partially null composite identity and conflicting
     * scalar values for one identity fail the operation. The root and every collection element must be a record; nested
     * collection components must be exact {@code List<Record>} shapes. This annotation is legal only for query execution
     * and cannot be combined with {@link RowMapper}, {@link RowReducer}, generated keys, or query traversal requests.
     */
    @Target(ElementType.METHOD)
    @Retention(RetentionPolicy.SOURCE)
    public @interface IdentityReducer {
        /**
         * Root-relative record-component paths that identify the root and every collection element scope.
         *
         * @return identity component paths
         */
        String[] identityPaths();
    }

    /**
     * Selects an application-provided {@link JdbcClient.RowMapper} service for one physical result row.
     * <p>
     * With a mapper class, generated code injects that exact service type. Without a class, generated code requires a
     * row-mapper service whose generic result type exactly matches the mapped repository type. When this annotation is
     * absent, supported records use deterministic generated mapping and do not consult mapper services.
     * <p>
     * A mapper service used by a singleton repository must be stateless or thread-safe. The mapper receives a scoped
     * {@link JdbcClient.Row} and never owns JDBC resources. This annotation is supported for query rows and generated-key
     * rows. It cannot be used for update counts or calls, and cannot be combined with {@link IdentityReducer} or
     * {@link RowReducer}.
     */
    @Target(ElementType.METHOD)
    @Retention(RetentionPolicy.SOURCE)
    public @interface RowMapper {
        /**
         * Concrete mapper service type, or {@link Void} to select a mapper by its generic result type.
         *
         * @return mapper service type
         */
        Class<?> value() default Void.class;
    }

    /**
     * Selects an application-provided {@link JdbcClient.RowReducer} for multi-row aggregation.
     * <p>
     * The reducer result type must exactly match the repository method return type. The reducer must be a concrete type
     * with an accessible no-argument constructor. Generated code creates a new reducer for each invocation, and the JDBC
     * provider retains ownership of every JDBC resource. This annotation is legal only for query execution, cannot be
     * used with a query traversal request, and cannot be combined with {@link RowMapper} or {@link IdentityReducer}.
     */
    @Target(ElementType.METHOD)
    @Retention(RetentionPolicy.SOURCE)
    public @interface RowReducer {
        /**
         * Reducer implementation selected for the repository method.
         *
         * @return reducer implementation type
         */
        Class<? extends JdbcClient.RowReducer<?>> value();
    }

    /**
     * Selects the standard JDBC type used to bind a repository method parameter.
     * <p>
     * This annotation is valid for ordinary query and update parameters and for stored-procedure or function
     * {@link InParameter IN} parameters. It changes only the JDBC binding metadata; it does not convert the Java value,
     * make a parameter nullable, or expand the provider's supported declarative scalar types. The generated repository
     * calls {@link JdbcClient.Statement#bind(int, Object, java.sql.SQLType)} for every SQL position occupied by the
     * annotated parameter.
     * <p>
     * {@link JDBCType#NULL} and {@link JDBCType#REF_CURSOR} are not input value types and are rejected during code
     * generation.
     */
    @Target(ElementType.PARAMETER)
    @Retention(RetentionPolicy.SOURCE)
    public @interface BindType {
        /**
         * Standard JDBC type supplied to the driver when binding this parameter.
         *
         * @return standard JDBC input type
         */
        JDBCType value();
    }

    /**
     * Declares a stored-procedure or function input parameter.
     * <p>
     * For named call SQL, {@link #name()} locates a unique marker; when omitted, the Java parameter name is used. An
     * optional {@link #index()} may assert the resolved one-based JDBC position. For positional call SQL, {@code index}
     * is required and {@code name} must be omitted. The annotated repository parameter supplies the non-null input value.
     * Add {@link BindType} to the same Java parameter only when the driver must not infer the input type.
     */
    @Target(ElementType.PARAMETER)
    @Retention(RetentionPolicy.SOURCE)
    public @interface InParameter {
        /**
         * Named marker and logical parameter name.
         *
         * @return marker name, or an empty string to use the Java parameter name for named SQL or {@link #index()} for
         *         positional SQL
         */
        String name() default "";

        /**
         * One-based JDBC parameter position.
         *
         * @return JDBC position, or {@code -1} when {@link #name()} locates the parameter
         */
        int index() default -1;
    }

    /**
     * Declares a stored-procedure or function input/output parameter.
     * <p>
     * The annotated repository parameter supplies the non-null input value and its declared Java type defines the
     * scalar output type. The generated repository binds and registers the same physical JDBC position. For named call
     * SQL, {@link #name()} locates a marker and defaults to the Java parameter name; {@link #index()} may additionally
     * assert its position. For positional call SQL, {@code index} locates the position and {@code name} is the optional
     * logical output name, defaulting to the Java parameter name.
     */
    @Target(ElementType.PARAMETER)
    @Retention(RetentionPolicy.SOURCE)
    public @interface InOutParameter {
        /**
         * Named marker and logical output name.
         *
         * @return marker and logical output name, or an empty string to use the Java parameter name
         */
        String name() default "";

        /**
         * One-based JDBC parameter position.
         *
         * @return JDBC position, or {@code -1} when {@link #name()} locates the parameter
         */
        int index() default -1;

        /**
         * JDBC type code used for input binding and output registration.
         *
         * @return a {@link java.sql.Types} or vendor type code
         */
        int jdbcType();

        /**
         * Optional database type name used by JDBC output registration. A declaration cannot configure both a database
         * type name and {@link #scale()}.
         *
         * @return database type name, or an empty string for ordinary registration
         */
        String typeName() default "";

        /**
         * Optional scale used to bind and register a numeric input/output parameter. A declaration cannot configure both
         * a scale and {@link #typeName()}.
         *
         * @return non-negative scale, or {@code -1} when no scale is configured
         */
        int scale() default -1;
    }

    /**
     * Declares a stored-procedure output parameter.
     * <p>
     * Scalar outputs declare a supported {@link #javaType()} and may be returned as a detached scalar, optional scalar,
     * or matching record. A cursor output selects {@link OutputKind#CURSOR}, leaves {@code javaType} as {@link Void}, and
     * is consumed only through the callback-scoped call output view. Cursor kind is explicit because a JDBC driver may
     * require either {@link java.sql.Types#REF_CURSOR} or a vendor-specific cursor type code.
     */
    @Target(ElementType.METHOD)
    @Retention(RetentionPolicy.SOURCE)
    @Repeatable(OutParameters.class)
    public @interface OutParameter {
        /**
         * Logical output name and, for named SQL, marker name.
         *
         * @return non-blank output name
         */
        String name();

        /**
         * One-based JDBC parameter position.
         *
         * @return JDBC position, or {@code -1} when {@link #name()} locates the parameter
         */
        int index() default -1;

        /**
         * JDBC type code used for output registration.
         *
         * @return a {@link java.sql.Types} or vendor type code
         */
        int jdbcType();

        /**
         * Supported Java type for a scalar output.
         *
         * @return scalar Java type, or {@link Void} for a cursor output
         */
        Class<?> javaType() default Void.class;

        /**
         * Optional database type name used by JDBC output registration. A declaration cannot configure both a database
         * type name and {@link #scale()}.
         *
         * @return database type name, or an empty string for ordinary registration
         */
        String typeName() default "";

        /**
         * Optional scale used by JDBC output registration. A declaration cannot configure both a scale and
         * {@link #typeName()}.
         *
         * @return non-negative scale, or {@code -1} when no scale is configured
         */
        int scale() default -1;

        /**
         * Output value kind.
         *
         * @return scalar or cursor output kind
         */
        OutputKind kind() default OutputKind.SCALAR;
    }

    /**
     * Java repeatable-annotation container for {@link OutParameter}.
     * <p>
     * Applications normally repeat {@code @Jdbc.OutParameter}; they do not use this container directly.
     */
    @Target(ElementType.METHOD)
    @Retention(RetentionPolicy.SOURCE)
    public @interface OutParameters {
        /**
         * Output declarations.
         *
         * @return output declarations
         */
        OutParameter[] value();
    }

    /**
     * Declares the return value of a JDBC function.
     * <p>
     * A function return always occupies JDBC position {@code 1}; its position is deliberately not configurable. A
     * scalar return may use detached or callback-scoped mode. A cursor return selects {@link OutputKind#CURSOR}, declares
     * {@link Void} as its Java type, and requires callback-scoped consumption.
     */
    @Target(ElementType.METHOD)
    @Retention(RetentionPolicy.SOURCE)
    public @interface ReturnParameter {
        /**
         * Logical output name and, for named function SQL, return marker.
         *
         * @return non-blank return name
         */
        String name();

        /**
         * JDBC type code used for output registration.
         *
         * @return a {@link java.sql.Types} or vendor type code
         */
        int jdbcType();

        /**
         * Supported Java type for a scalar return, or {@link Void} for a cursor return.
         *
         * @return Java return type
         */
        Class<?> javaType();

        /**
         * Optional database type name used by JDBC output registration. A declaration cannot configure both a database
         * type name and {@link #scale()}.
         *
         * @return database type name, or an empty string for ordinary registration
         */
        String typeName() default "";

        /**
         * Optional scale used by JDBC output registration. A declaration cannot configure both a scale and
         * {@link #typeName()}.
         *
         * @return non-negative scale, or {@code -1} when no scale is configured
         */
        int scale() default -1;

        /**
         * Function return kind.
         *
         * @return scalar or cursor return kind
         */
        OutputKind kind() default OutputKind.SCALAR;
    }
}
