/*
 * Copyright (c) 2026 Oracle and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.helidon.data.jdbc;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;

import io.helidon.data.DataException;

import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static java.util.UUID.randomUUID;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.contains;
import static org.hamcrest.Matchers.containsString;
import static org.hamcrest.Matchers.empty;
import static org.hamcrest.Matchers.is;
import static org.junit.jupiter.api.Assertions.assertThrows;

final class JdbcOperationsTest {

    private JdbcOperations jdbc;
    private JdbcClient client;
    private JdbcKernel kernel;

    private JdbcOperationsTest() {
        super();
    }

    @BeforeEach
    void setupDataSource() {
        JdbcDataSource ds = new JdbcDataSource();
        ds.setUrl("jdbc:h2:mem:" + randomUUID() + ";DB_CLOSE_DELAY=-1");
        this.jdbc = JdbcOperations.create(ds);
        this.client = JdbcClient.create(ds);
        this.kernel = JdbcKernel.create(ds);
        this.jdbc.update("""
                                 CREATE TABLE pokemon (
                                     id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name VARCHAR(64) NOT NULL
                                 )
                         """);
    }

    @Test
    void testList() {
        insert("Bulbasaur");
        insert("Ivysaur");

        List<String> names = jdbc.list("""
                                               SELECT name
                                               FROM pokemon
                                               ORDER BY id
                                       """,
                                       row -> row.getString("name"));

        assertThat(names, contains("Bulbasaur", "Ivysaur"));
    }

    @Test
    void testListReduced() {
        List<Contact> contacts = jdbc.listReduced("""
                                                          SELECT 1 AS contact_id,
                                                                 'Ada' AS contact_name,
                                                                 10 AS phone_id,
                                                                 '111' AS phone
                                                          UNION ALL
                                                          SELECT 1 AS contact_id,
                                                                 'Ada' AS contact_name,
                                                                 11 AS phone_id,
                                                                 '222' AS phone
                                                          UNION ALL
                                                          SELECT 2 AS contact_id,
                                                                 'Bob' AS contact_name,
                                                                 CAST(NULL AS INTEGER) AS phone_id,
                                                                 CAST(NULL AS VARCHAR) AS phone
                                                          ORDER BY contact_id, phone_id
                                                  """,
                                                  JdbcBinder.none(),
                                                  new ContactReducer());

        assertThat(contacts, contains(new Contact(1L,
                                                  "Ada",
                                                  List.of(new Phone(10L, "111"),
                                                          new Phone(11L, "222"))),
                                      new Contact(2L, "Bob", List.of())));
    }

    @Test
    void testOptional() {
        insert("Bulbasaur");

        Optional<String> name = jdbc.optional("""
                                                     SELECT name
                                                     FROM pokemon
                                                     WHERE name = ?
                                             """,
                                             statement -> statement.setString(1, "Bulbasaur"),
                                             row -> row.getString("name"));
        Optional<String> missing = jdbc.optional("""
                                                        SELECT name
                                                        FROM pokemon
                                                        WHERE name = ?
                                                """,
                                                statement -> statement.setString(1, "Missing"),
                                                row -> row.getString("name"));

        assertThat(name.orElseThrow(), is("Bulbasaur"));
        assertThat(missing.stream().toList(), empty());
    }

    @Test
    void testOne() {
        insert("Bulbasaur");

        String name = jdbc.one("""
                                      SELECT name
                                      FROM pokemon
                                      WHERE name = ?
                              """,
                              statement -> statement.setString(1, "Bulbasaur"),
                              row -> row.getString("name"));

        assertThat(name, is("Bulbasaur"));
    }

    @Test
    void testOneWithoutRows() {
        DataException ex = assertThrows(DataException.class,
                                        () -> jdbc.one("""
                                                               SELECT name
                                                               FROM pokemon
                                                               WHERE name = ?
                                                       """,
                                                       statement -> statement.setString(1, "Missing"),
                                                       row -> row.getString("name")));

        assertThat(ex.getMessage(), is("JDBC query returned no rows."));
    }

    @Test
    void testSqlFailureIsTranslated() {
        DataException ex = assertThrows(DataException.class,
                                        () -> jdbc.list("""
                                                               SELECT missing_column
                                                               FROM missing_table
                                                       """,
                                                       JdbcBinder.none(),
                                                       row -> row.getString("missing_column")));

        assertThat(ex.getMessage(), is("JDBC query failed."));
    }

    @Test
    void testMappingFailureIsTranslated() {
        insert("Bulbasaur");

        DataException ex = assertThrows(DataException.class,
                                        () -> jdbc.list("""
                                                               SELECT name
                                                               FROM pokemon
                                                       """,
                                                       JdbcBinder.none(),
                                                       row -> row.getString("missing_column")));

        assertThat(ex.getMessage(), is("JDBC query failed."));
    }

    @Test
    void testOptionalWithTooManyRows() {
        insert("Bulbasaur");
        insert("Ivysaur");

        DataException ex = assertThrows(DataException.class,
                                        () -> jdbc.optional("""
                                                                   SELECT name
                                                                   FROM pokemon
                                                           """,
                                                           JdbcBinder.none(),
                                                           row -> row.getString("name")));

        assertThat(ex.getMessage(), is("JDBC query returned more than one row."));
    }

    @Test
    void testGeneratedKey() {
        Optional<Integer> id = jdbc.generatedKey("""
                                                        INSERT INTO pokemon (name)
                                                        VALUES (?)
                                                """,
                                                statement -> statement.setString(1, "Bulbasaur"),
                                                row -> row.getInt(1),
                                                "id");

        assertThat(id.orElseThrow(), is(1));
    }

    @Test
    void testGeneratedKeyRequiresGeneratedKeyPlan() {
        DataException ex = assertThrows(DataException.class,
                                        () -> jdbc.generatedKey(JdbcStatementPlan.update("""
                                                INSERT INTO pokemon (name)
                                                VALUES (?)
                                                """),
                                                                statement -> statement.setString(1, "Bulbasaur"),
                                                                row -> row.getInt(1)));

        assertThat(ex.getMessage(), is("JDBC generated-key update requires a generated-keys statement plan."));
    }

    @Test
    void testPlanOptions() {
        insert("Bulbasaur");
        insert("Ivysaur");

        JdbcStatementPlan plan = JdbcStatementPlan.query("""
                                                                 SELECT name
                                                                 FROM pokemon
                                                                 ORDER BY id
                                                         """)
                .withOptions(new JdbcStatementOptions(1, 1, 1));

        List<String> names = jdbc.list(plan, JdbcBinder.none(), row -> row.getString("name"));

        assertThat(names, is(List.of("Bulbasaur")));
    }

    @Test
    void testFluentClient() {
        client.update("""
                              INSERT INTO pokemon (name)
                              VALUES (?)
                      """)
                .bind(1, "Bulbasaur")
                .execute();
        client.update("""
                              INSERT INTO pokemon (name)
                              VALUES (?)
                      """)
                .bind(1, "Ivysaur")
                .execute();

        List<String> names = client.query("""
                                                  SELECT name
                                                  FROM pokemon
                                                  ORDER BY id
                                          """)
                .fetchSize(1)
                .maxRows(1)
                .list(row -> row.string("name"));

        assertThat(names, is(List.of("Bulbasaur")));
    }

    @Test
    void testFluentGeneratedKey() {
        Optional<Integer> id = client.update("""
                                                     INSERT INTO pokemon (name)
                                                     VALUES (?)
                                             """)
                .bind(1, "Bulbasaur")
                .generatedKey(row -> row.intValue("id"), "id");

        assertThat(id.orElseThrow(), is(1));
    }

    @Test
    void testStoredProcedurePlaceholder() {
        DataException ex = assertThrows(DataException.class,
                                        () -> kernel.executePlaceholder(
                                                JdbcStatementPlan.call("{call update_pokemon(?)}")));

        assertThat(ex.getMessage(), containsString("stored procedure execution is reserved"));
        assertThat(ex.getMessage(), containsString("CallableStatement"));
        assertThat(ex.getMessage(), containsString("OUT parameters"));
    }

    @Test
    void testBatchPlaceholder() {
        DataException ex = assertThrows(DataException.class,
                                        () -> kernel.executePlaceholder(JdbcStatementPlan.batch("""
                                                INSERT INTO pokemon (name)
                                                VALUES (?)
                                                """)));

        assertThat(ex.getMessage(), containsString("batch execution is reserved"));
        assertThat(ex.getMessage(), containsString("addBatch"));
        assertThat(ex.getMessage(), containsString("JdbcBatchExecutionResults"));
    }

    @Test
    void testMultiStatementPlaceholder() {
        JdbcStatementPlan insert = JdbcStatementPlan.update("""
                                                                    INSERT INTO pokemon (name)
                                                                    VALUES (?)
                                                            """);
        JdbcStatementPlan select = JdbcStatementPlan.query("""
                                                                   SELECT name
                                                                   FROM pokemon
                                                           """);
        JdbcMethodPlan plan = JdbcMethodPlan.of(List.of(insert, select));

        DataException ex = assertThrows(DataException.class,
                                        () -> kernel.executePlaceholder(plan));

        assertThat(ex.getMessage(), containsString("multi-statement repository methods are reserved"));
        assertThat(ex.getMessage(), containsString("ordered statement plans"));
    }

    private void insert(String name) {
        long updated = jdbc.update("""
                                           INSERT INTO pokemon (name)
                                           VALUES (?)
                                   """,
                                   statement -> statement.setString(1, name));
        assertThat(updated, is(1L));
    }

    private record Contact(long id, String name, List<Phone> phones) {
    }

    private record Phone(long id, String phone) {
    }

    private static final class ContactReducer implements JdbcRowReducer<Contact> {
        private final Map<Long, ContactAccumulator> contacts = new LinkedHashMap<>();

        @Override
        public void add(JdbcResultSetRowView row) throws java.sql.SQLException {
            long contactId = row.getLong("contact_id");
            ContactAccumulator contact = contacts.get(contactId);
            if (contact == null) {
                contact = new ContactAccumulator(contactId, row.getString("contact_name"));
                contacts.put(contactId, contact);
            }

            Object phoneId = row.getObject("phone_id");
            if (phoneId != null) {
                contact.addPhone(((Number) phoneId).longValue(), row.getString("phone"));
            }
        }

        @Override
        public List<Contact> result() {
            List<Contact> result = new ArrayList<>(contacts.size());
            contacts.values().forEach(contact -> result.add(contact.finish()));
            return result;
        }
    }

    private static final class ContactAccumulator {
        private final long id;
        private final String name;
        private final Map<Long, Phone> phones = new LinkedHashMap<>();

        private ContactAccumulator(long id, String name) {
            this.id = id;
            this.name = name;
        }

        private void addPhone(long id, String phone) {
            phones.putIfAbsent(id, new Phone(id, phone));
        }

        private Contact finish() {
            return new Contact(id, name, List.copyOf(phones.values()));
        }
    }
}
