/*
 * Copyright (c) 2026 Oracle and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.helidon.data.jdbc;

import java.util.List;
import java.util.Optional;
import java.util.UUID;

import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.Test;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.contains;
import static org.hamcrest.Matchers.is;

class JdbcClientGeneratedKeysTest {

    @Test
    void mapsGeneratedKeysRequestedByTerminalMethod() {
        JdbcClient client = client();
        client.execute("""
                       CREATE TABLE pokemon (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           name VARCHAR(64)
                       )
                       """)
                .updateCount();

        List<Long> ids = client.execute("INSERT INTO pokemon(name) VALUES (:name)")
                .param("name", "Pikachu")
                .generatedKeys(row -> row.value(1, Long.class));

        assertThat(ids, contains(1L));
    }

    @Test
    void mapsSingleGeneratedKeyWithColumnNames() {
        JdbcClient client = client();
        client.execute("""
                       CREATE TABLE pokemon (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           name VARCHAR(64)
                       )
                       """)
                .updateCount();

        Long id = client.execute("INSERT INTO pokemon(name) VALUES (:name)")
                .param("name", "Pikachu")
                .generatedKeyColumns("ID")
                .generatedKey(row -> row.value(1, Long.class));

        assertThat(id, is(1L));
    }

    @Test
    void mapsSingleGeneratedKeyWithColumnIndexes() {
        JdbcClient client = client();
        client.execute("""
                       CREATE TABLE pokemon (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           name VARCHAR(64)
                       )
                       """)
                .updateCount();

        Long id = client.execute("INSERT INTO pokemon(name) VALUES (:name)")
                .param("name", "Pikachu")
                .generatedKeyColumns(1)
                .generatedKey(row -> row.value(1, Long.class));

        assertThat(id, is(1L));
    }

    @Test
    void mapsOptionalGeneratedKey() {
        JdbcClient client = client();
        client.execute("""
                       CREATE TABLE pokemon (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           name VARCHAR(64)
                       )
                       """)
                .updateCount();

        Optional<Long> id = client.execute("INSERT INTO pokemon(name) VALUES (:name)")
                .param("name", "Pikachu")
                .optionalGeneratedKey(row -> row.value(1, Long.class));

        assertThat(id, is(Optional.of(1L)));
    }

    private static JdbcClient client() {
        JdbcDataSource dataSource = new JdbcDataSource();
        dataSource.setUrl("jdbc:h2:mem:" + UUID.randomUUID() + ";DB_CLOSE_DELAY=-1");
        return new JdbcClientImpl("test", dataSource, Optional.empty());
    }
}
