/*
 * Copyright (c) 2026 Oracle and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.helidon.data.jdbc;

import java.sql.ResultSet;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

import io.helidon.data.DataException;
import io.helidon.data.NonUniqueResultException;

import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.Test;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.contains;
import static org.hamcrest.Matchers.is;
import static org.junit.jupiter.api.Assertions.assertThrows;

class JdbcClientStatementOptionsTest {

    @Test
    void appliesQueryStatementOptions() {
        JdbcClient client = client();
        createPokemon(client);

        List<String> names = client.execute("SELECT name FROM pokemon ORDER BY id")
                .fetchSize(1)
                .maxRows(1)
                .queryTimeout(1)
                .resultSet(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY)
                .list(row -> row.value("name", String.class));

        assertThat(names, contains("Pikachu"));
    }

    @Test
    void appliesResultSetHoldabilityOption() {
        JdbcClient client = client();
        createPokemon(client);

        List<String> names = client.execute("SELECT name FROM pokemon ORDER BY id")
                .resultSet(ResultSet.TYPE_FORWARD_ONLY,
                           ResultSet.CONCUR_READ_ONLY,
                           ResultSet.CLOSE_CURSORS_AT_COMMIT)
                .list(row -> row.value("name", String.class));

        assertThat(names, contains("Pikachu", "Raichu"));
    }

    @Test
    void projectsReadColumnsByLabel() {
        JdbcClient client = client();
        createPokemon(client);

        List<String> names = client.execute("SELECT id, name FROM pokemon ORDER BY id")
                .readColumns("name")
                .list(row -> {
                    assertThat(row.columnCount(), is(1));
                    assertThrows(DataException.class, () -> row.value("id"));
                    return row.value("name", String.class);
                });

        assertThat(names, contains("Pikachu", "Raichu"));
    }

    @Test
    void projectsReadColumnsByIndex() {
        JdbcClient client = client();
        createPokemon(client);

        List<String> names = client.execute("SELECT id, name FROM pokemon ORDER BY id")
                .readColumns(2)
                .list(row -> {
                    assertThat(row.columnCount(), is(1));
                    return row.value(1, String.class);
                });

        assertThat(names, contains("Pikachu", "Raichu"));
    }

    @Test
    void rejectsMissingProjectedColumnLabel() {
        JdbcClient client = client();
        createPokemon(client);

        assertThrows(DataException.class,
                     () -> client.execute("SELECT id, name FROM pokemon ORDER BY id")
                             .readColumns("missing")
                             .list(row -> row.value(1)));
    }

    @Test
    void singleDetectsNonUniqueResultWithBoundedMaterialization() {
        JdbcClient client = client();
        createPokemon(client);

        assertThrows(NonUniqueResultException.class,
                     () -> client.execute("SELECT name FROM pokemon ORDER BY id")
                             .single(row -> row.value(1, String.class)));
    }

    private static void createPokemon(JdbcClient client) {
        client.execute("""
                       CREATE TABLE pokemon (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           name VARCHAR(64)
                       )
                       """)
                .updateCount();
        client.execute("INSERT INTO pokemon(name) VALUES (:name)")
                .param("name", "Pikachu")
                .updateCount();
        client.execute("INSERT INTO pokemon(name) VALUES (:name)")
                .param("name", "Raichu")
                .updateCount();
    }

    private static JdbcClient client() {
        JdbcDataSource dataSource = new JdbcDataSource();
        dataSource.setUrl("jdbc:h2:mem:" + UUID.randomUUID() + ";DB_CLOSE_DELAY=-1");
        return new JdbcClientImpl("test", dataSource, Optional.empty());
    }
}
