/*
 * Copyright (c) 2026 Oracle and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.helidon.data.jdbc;

import java.sql.JDBCType;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.atomic.AtomicReference;

import io.helidon.data.DataException;
import io.helidon.data.NoResultException;
import io.helidon.data.NonUniqueResultException;

import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertInstanceOf;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

class JdbcRunnerTest {
    private JdbcClient client;

    @BeforeEach
    void setUp() throws SQLException {
        JdbcDataSource dataSource = new JdbcDataSource();
        dataSource.setURL("jdbc:h2:mem:jdbc_runner;DB_CLOSE_DELAY=-1");
        try (var connection = dataSource.getConnection();
             var statement = connection.createStatement()) {
            statement.execute("DROP TABLE IF EXISTS USERS");
            statement.execute("CREATE TABLE USERS (ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, NAME VARCHAR(80))");
            statement.execute("INSERT INTO USERS (NAME) VALUES ('Ada'), ('Grace'), ('Linus')");
        }
        client = new JdbcClientImpl(dataSource);
    }

    @Test
    void mapsCardinalityAndBindsPositionally() {
        assertEquals(List.of("Ada", "Grace", "Linus"),
                     client.create("SELECT NAME FROM USERS ORDER BY ID").map(String.class).list());
        assertEquals(Optional.of("Grace"),
                     client.create("SELECT NAME FROM USERS WHERE ID = ?")
                             .bind(1, 2L)
                             .map(String.class)
                             .optional());
        assertThrows(NoResultException.class,
                     () -> client.create("SELECT NAME FROM USERS WHERE ID = ?")
                             .bind(1, -1L)
                             .map(String.class)
                             .one());
        assertThrows(NonUniqueResultException.class,
                     () -> client.create("SELECT NAME FROM USERS").map(String.class).one());
        assertNull(client.create("SELECT CAST(NULL AS BIGINT)").map(Long.class).one());
        assertThrows(DataException.class,
                     () -> client.create("SELECT CAST(NULL AS BIGINT)").map(long.class).one());
    }

    @Test
    void executesUpdatesAndGeneratedKeysThroughSameStatementStage() {
        assertEquals(1,
                     client.create("UPDATE USERS SET NAME = ? WHERE ID = ?")
                             .bind(1, "Margaret", JDBCType.VARCHAR)
                             .bind(2, 1L)
                             .execute());

        long id = client.create("INSERT INTO USERS (NAME) VALUES (?)")
                .bind(1, "Barbara")
                .generatedKeys(row -> row.required(1, Long.class))
                .one();

        assertEquals(Optional.of("Barbara"),
                     client.create("SELECT NAME FROM USERS WHERE ID = ?")
                             .bind(1, id)
                             .map(String.class)
                             .optional());

        long nullNameId = client.create("INSERT INTO USERS (NAME) VALUES (?)")
                .bindNull(1, JDBCType.VARCHAR)
                .generatedKeys(row -> row.required("ID", Long.class), "ID")
                .one();
        assertNull(client.create("SELECT NAME FROM USERS WHERE ID = ?")
                           .bind(1, nullNameId)
                           .map(String.class)
                           .one());
    }

    @Test
    void appliesRegularRequestsToCardinalityAndGeneratedKeyTerminals() {
        JdbcQueryRequest request = JdbcQueryRequest.builder().fetchSize(8).build();

        assertEquals(List.of("Ada", "Grace", "Linus"),
                     client.create("SELECT NAME FROM USERS ORDER BY ID").map(String.class).list(request));
        assertEquals(Optional.of("Ada"),
                     client.create("SELECT NAME FROM USERS WHERE ID = 1")
                             .map(String.class)
                             .optional(JdbcQueryRequest.defaults()));
        assertEquals("Grace",
                     client.create("SELECT NAME FROM USERS WHERE ID = 2")
                             .map(String.class)
                             .one(request));

        long id = client.create("INSERT INTO USERS (NAME) VALUES (?)")
                .bind(1, "Edsger")
                .generatedKeys(row -> row.required(1, Long.class))
                .one(request);
        assertEquals("Edsger",
                     client.create("SELECT NAME FROM USERS WHERE ID = ?")
                             .bind(1, id)
                             .map(String.class)
                             .one());
    }

    @Test
    void reducesRowsWithoutExposingResultSet() {
        int count = client.create("SELECT ID, NAME FROM USERS ORDER BY ID")
                .reduce(new JdbcClient.RowReducer<>() {
                    private int rows;

                    @Override
                    public void accept(JdbcClient.Row row) {
                        row.required(1, Long.class);
                        row.required(2, String.class);
                        rows++;
                    }

                    @Override
                    public Integer finish() {
                        return rows;
                    }
                });

        assertEquals(3, count);
    }

    @Test
    void appliesARegularRequestToReduction() {
        int count = client.create("SELECT ID FROM USERS ORDER BY ID")
                .reduce(new JdbcClient.RowReducer<>() {
                    private int rows;

                    @Override
                    public void accept(JdbcClient.Row row) {
                        row.required(1, Long.class);
                        rows++;
                    }

                    @Override
                    public Integer finish() {
                        return rows;
                    }
                }, JdbcQueryRequest.builder().fetchSize(4).build());

        assertEquals(3, count);
    }

    @Test
    void supportsProviderOwnedPushTraversal() {
        List<String> pushed = new ArrayList<>();
        client.create("SELECT NAME FROM USERS ORDER BY ID")
                .map(String.class)
                .visitAll(JdbcQueryRequest.visitAll(pushed::add));
        assertEquals(List.of("Ada", "Grace", "Linus"), pushed);

        List<String> stopped = new ArrayList<>();
        boolean exhausted = client.create("SELECT NAME FROM USERS ORDER BY ID")
                .map(String.class)
                .visitWhile(JdbcQueryRequest.visitWhile(value -> {
                    stopped.add(value);
                    return stopped.size() < 2;
                }));
        assertFalse(exhausted);
        assertEquals(List.of("Ada", "Grace"), stopped);
    }

    @Test
    void reusesAnImmutableRequestAcrossSequentialExecutions() {
        List<String> values = new ArrayList<>();
        JdbcQueryRequest.VisitAll<String> request = JdbcQueryRequest.visitAll(values::add);

        client.create("SELECT NAME FROM USERS ORDER BY ID").map(String.class).visitAll(request);
        client.create("SELECT NAME FROM USERS ORDER BY ID").map(String.class).visitAll(request);

        assertEquals(List.of("Ada", "Grace", "Linus", "Ada", "Grace", "Linus"), values);

        JdbcQueryRequest regular = JdbcQueryRequest.builder().fetchSize(2).build();
        assertEquals(List.of("Ada", "Grace", "Linus"),
                     client.create("SELECT NAME FROM USERS ORDER BY ID").map(String.class).list(regular));
        assertEquals(List.of("Ada", "Grace", "Linus"),
                     client.create("SELECT NAME FROM USERS ORDER BY ID").map(String.class).list(regular));
    }

    @Test
    void traversesEmptyResultsAndReportsExhaustion() {
        List<String> pushed = new ArrayList<>();
        client.create("SELECT NAME FROM USERS WHERE ID < 0")
                .map(String.class)
                .visitAll(JdbcQueryRequest.visitAll(pushed::add));
        assertTrue(pushed.isEmpty());

        assertTrue(client.create("SELECT NAME FROM USERS WHERE ID < 0")
                           .map(String.class)
                           .visitWhile(JdbcQueryRequest.visitWhile(value -> false)));
    }

    @Test
    void nullTraversalActionDoesNotConsumeTheRowsStage() {
        JdbcClient.Rows<String> rows = client.create("SELECT NAME FROM USERS ORDER BY ID").map(String.class);

        assertThrows(NullPointerException.class, () -> rows.visitAll(null));
        List<String> values = new ArrayList<>();
        rows.visitAll(JdbcQueryRequest.visitAll(values::add));

        assertEquals(List.of("Ada", "Grace", "Linus"), values);
        assertThrows(IllegalStateException.class,
                     () -> rows.visitAll(JdbcQueryRequest.visitAll(ignored -> { })));

        JdbcClient.Rows<String> regularRows = client.create("SELECT NAME FROM USERS ORDER BY ID").map(String.class);
        assertThrows(NullPointerException.class, () -> regularRows.list(null));
        assertEquals(List.of("Ada", "Grace", "Linus"), regularRows.list(JdbcQueryRequest.defaults()));
    }

    @Test
    void confinesRowViewsToTheirSynchronousCallbacks() {
        AtomicReference<JdbcClient.Row> retainedRow = new AtomicReference<>();
        client.create("SELECT ID FROM USERS WHERE ID = 1")
                .map(row -> {
                    retainedRow.set(row);
                    return row.required(1, Long.class);
                })
                .one();
        assertThrows(IllegalStateException.class, () -> retainedRow.get().get(1, Long.class));

    }

    @Test
    void validatesBeforeBorrowAndEnforcesSingleTerminal() {
        JdbcClient.Statement missing = client.create("SELECT NAME FROM USERS WHERE ID = ?");
        assertThrows(IllegalStateException.class, () -> missing.map(String.class).list());

        JdbcClient.Rows<String> rows = client.create("SELECT NAME FROM USERS WHERE ID = 1").map(String.class);
        assertEquals(List.of("Ada"), rows.list());
        assertThrows(IllegalStateException.class, rows::list);

        assertThrows(IllegalArgumentException.class, () -> client.create("SELECT :name"));
        assertThrows(IllegalArgumentException.class,
                     () -> client.create("SELECT NAME FROM USERS WHERE ID = ?").bind(2, 1L));
        assertThrows(NullPointerException.class,
                     () -> client.create("SELECT NAME FROM USERS WHERE ID = ?").bind(1, null));
        assertThrows(IllegalArgumentException.class,
                     () -> client.create("INSERT INTO USERS (NAME) VALUES ('duplicate key names')")
                             .generatedKeys(row -> row.required(1, Long.class), "ID", "id"));
    }

    @Test
    void preservesSqlExceptionDetails() {
        DataException error = assertThrows(DataException.class,
                                           () -> client.create("SELECT MISSING FROM USERS").map(String.class).list());

        SQLException cause = assertInstanceOf(SQLException.class, error.getCause());
        assertTrue(error.getMessage().contains("SQLState="));
        assertTrue(error.getMessage().contains("vendorCode=" + cause.getErrorCode()));
    }
}
