/*
 * Copyright (c) 2026 Oracle and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.helidon.data.jdbc;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;
import java.util.Set;

import javax.sql.DataSource;

import io.helidon.common.Weighted;
import io.helidon.common.types.ResolvedType;
import io.helidon.common.types.TypeName;
import io.helidon.config.Config;
import io.helidon.config.ConfigSources;
import io.helidon.service.registry.Qualifier;
import io.helidon.service.registry.Service;
import io.helidon.service.registry.ServiceInstance;

import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import static java.util.UUID.randomUUID;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.contains;
import static org.hamcrest.Matchers.is;

final class JdbcOperationsFactoryTest {

    @TempDir
    private Path tempDir;

    private JdbcOperationsFactoryTest() {
        super();
    }

    @Test
    void testNoPersistenceUnitConfigCreatesNoJdbcOperations() {
        JdbcOperationsFactory factory = new JdbcOperationsFactory(List::of, Config::empty);

        List<Service.QualifiedInstance<JdbcOperations>> instances = factory.services();

        assertThat(instances.size(), is(0));
    }

    @Test
    void testNamedPersistenceUnitRunsInitScript() throws IOException {
        Path initScript = tempDir.resolve("init.sql");
        Files.writeString(initScript, """
                CREATE TABLE pokemon (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name VARCHAR(64) NOT NULL
                );
                INSERT INTO pokemon (name) VALUES ('Bulbasaur');
                """);
        DataSource dataSource = dataSource();
        Config config = Config.just(ConfigSources.create(Map.of(
                "data.persistence-units.jdbc.0.name", "pokemon",
                "data.persistence-units.jdbc.0.data-source", "database",
                "data.persistence-units.jdbc.0.init-script", initScript.toString())));
        JdbcOperationsFactory factory = factory(config, dataSource("database", dataSource));

        List<Service.QualifiedInstance<JdbcOperations>> instances = factory.services();

        assertThat(instances.size(), is(3));
        assertThat(unqualified(instances), is(named(instances, "pokemon")));
        JdbcOperations jdbc = named(instances, "pokemon");
        List<String> names = jdbc.list("SELECT name FROM pokemon", row -> row.getString("name"));

        assertThat(names, contains("Bulbasaur"));
    }

    @Test
    void testInlineConnectionPersistenceUnitRunsInitScript() throws IOException {
        Path initScript = tempDir.resolve("inline-init.sql");
        Files.writeString(initScript, """
                CREATE TABLE pokemon (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name VARCHAR(64) NOT NULL
                );
                INSERT INTO pokemon (name) VALUES ('Charmander');
                """);
        Config config = Config.just(ConfigSources.create(Map.of(
                "data.persistence-units.jdbc.0.name", "pokemon",
                "data.persistence-units.jdbc.0.connection.url", "jdbc:h2:mem:" + randomUUID() + ";DB_CLOSE_DELAY=-1",
                "data.persistence-units.jdbc.0.connection.jdbc-driver-class-name", "org.h2.Driver",
                "data.persistence-units.jdbc.0.init-script", initScript.toString())));
        JdbcOperationsFactory factory = new JdbcOperationsFactory(List::of, () -> config);

        List<Service.QualifiedInstance<JdbcOperations>> instances = factory.services();

        assertThat(instances.size(), is(3));
        assertThat(unqualified(instances), is(named(instances, "pokemon")));
        JdbcOperations jdbc = named(instances, "pokemon");
        List<String> names = jdbc.list("SELECT name FROM pokemon", row -> row.getString("name"));

        assertThat(names, contains("Charmander"));
    }

    private static JdbcOperationsFactory factory(Config config, ServiceInstance<DataSource> dataSource) {
        return new JdbcOperationsFactory(() -> List.of(dataSource), () -> config);
    }

    private static JdbcOperations named(List<Service.QualifiedInstance<JdbcOperations>> instances, String name) {
        Qualifier qualifier = Qualifier.createNamed(name);
        return instances.stream()
                .filter(it -> it.qualifiers().contains(qualifier))
                .findFirst()
                .orElseThrow()
                .get();
    }

    private static JdbcOperations unqualified(List<Service.QualifiedInstance<JdbcOperations>> instances) {
        return instances.stream()
                .filter(it -> it.qualifiers().isEmpty())
                .findFirst()
                .orElseThrow()
                .get();
    }

    private static ServiceInstance<DataSource> dataSource(String name, DataSource dataSource) {
        return new TestServiceInstance<>(dataSource, Set.of(Qualifier.createNamed(name)));
    }

    private static DataSource dataSource() {
        JdbcDataSource dataSource = new JdbcDataSource();
        dataSource.setUrl("jdbc:h2:mem:" + randomUUID() + ";DB_CLOSE_DELAY=-1");
        return dataSource;
    }

    private record TestServiceInstance<T>(T instance, Set<Qualifier> qualifiers) implements ServiceInstance<T> {

        @Override
        public T get() {
            return instance;
        }

        @Override
        public Set<ResolvedType> contracts() {
            return Set.of();
        }

        @Override
        public TypeName scope() {
            return Service.Singleton.TYPE;
        }

        @Override
        public double weight() {
            return Weighted.DEFAULT_WEIGHT;
        }

        @Override
        public TypeName serviceType() {
            return TypeName.create(instance.getClass());
        }
    }
}
